### ISSUE TITLE
Job success/failure handling

### ISSUE THREAD

**Issue by selwin** [nvie/rq#206]
Hi there,

I'd like to propose a new API for handling job success/failure. My API idea is as such:

```python
def handle_success(job):
    pass

def handle_failure(job):
    pass

q.enqueue(f, on_success=handle_success, on_failure=handle_failure)
```

The goal of these new APIs is to allow the decoupling of job processing/management related code from actual application code, as outlined by @acjohnson55 in https://github.com/nvie/rq/issues/189 . https://github.com/ui/django-rq/issues/17 is also another issue that could be solved by the introduction of these APIs.

One thing that we'd have to consider is consistency, as we already have a queue level exception handler in ``Queue(connection, exc_handler=handler)``. If I'm not mistaken (correct me if I'm wrong), the primary use case we had in mind for ``exc_handler`` was for logging purposes. However, now that we are using Python's ``logging``, it can be easily configured by passing in a config file (issue #166).

So my proposal is to implement an API to allow the use of custom success/failure handler on the job level. Optionally, we can choose to deprecate ``exc_handler`` in later releases.

Thoughts?

**Comment by nnbosko** [comment]
Have there been any updates on this?

**Comment by selwin** [comment]
Yes, you can now pass in multiple ``--exception-handler`` argument to `rqworker` cli command. See https://github.com/nvie/rq/blob/master/rq/cli/cli.py#L151
