### ISSUE TITLE
Can not mock rq's redis connection with mockredis

### ISSUE THREAD

**Issue by zgoda** [nvie/rq#282]
Because of check if connection is instance of `StrictRedis` in `rq.compat.connection.patch_connection()`. Is this check really necessary?

**Comment by yrik** [comment]
@robodude666 could you show how you patch `patch_connection `?
I have the same issue..

**Comment by homeworkprod** [comment]
I struggle with this as well. Bummer.

**Comment by homeworkprod** [comment]
For my simple use case – avoiding the need for a running Redis server during tests – without any mock call verifications, this seems to work (Python 3.4.2, redis 2.10.3, rq 0.5.2):

```python
from unittest.mock import MagicMock

from redis import StrictRedis


class StrictRedisMock(MagicMock, StrictRedis):

    @classmethod
    def from_url(cls, arg):
        return cls()
```

The code under test creates `StrictRedis` instances via the `from_url` method. YMMV.

Apply like this:
```python

class SomeTest(SomeTestBase):

    @patch('redis.StrictRedis.from_url', StrictRedisMock.from_url)
    def setUp(self):
        super().setUp()

        # …
```

HTH

**Comment by homeworkprod** [comment]
For the record, I switched from the mock class using diamond inheritance to this:

```python
def strict_redis_client_from_url(url):
    mock = MagicMock()
    mock.__class__ = StrictRedis
    return mock
```

Usage:
```python
class SomeTest(SomeTestBase):

    @patch('redis.StrictRedis.from_url', strict_redis_client_from_url)
    def setUp(self):
        super().setUp()

        # …
```

That said, my two suggested approaches might have serious limitations I haven't (yet) hit.

**Comment by nvie** [comment]
I wish there was a better way for me to check this in `patch_connection`, but I don't think there is another way of distinguishing between `redis.StrictRedis` and `redis.Redis` other than using explicit `isinstance()` checks. If anyone has a better suggestion, I'd like to hear it.
