### ISSUE TITLE
Create Job before submit

### ISSUE THREAD

**Issue by wichert** [nvie/rq#327]
I use rq in what I suspect is a pretty common type of environment: a web framework (pyramid in my case) which wraps processing for each request in a separate transaction. When you enqueue a task during request processing you can hit two problems: 1) an enqueued task will still run if the transaction fails, and 2) a task may start running before the webapp commits the transaction and will have either outdated or missing data. For the common case I can work around that by delaying the enqueueing until after the transaction has committed successfully. Here is the code I use to do that:

```python
def enqueue(request, queue, func, *a, **kw):
    queue = request.registry.settings['_rq_queues'][queue]
    tx = transaction.get()
    def hook(status):
        if status:  # Only enqueue for successful transactions
            queue.enqueue_call(func, a, kw)
    tx.addAfterCommitHook(hook)
```

There is a problem with this approach though: for some API calls I need to return a job id to the caller, so the caller can later check if a job has finished and get its result. This does not work with the delay-until-post-commit approach since I don't get a job id until the job has been added to the queue. I can do that by side-stepping the standard API like this:

```python
def enqueue(request, queue, func, *a, **kw):
    queue = request.registry.settings['_rq_queues'][queue]
    tx = transaction.get()
    job = Job.create(func, a, kw, connection=queue.connection, status=Status.QUEUED)
    def hook(status):
        if status:  # Only enqueue for successful transactions
            queue.enqueue_job(job)
    tx.addAfterCommitHook(hook)
    return job
```

This works, but copies more implementation details from rq into my code than I am comfortable with. Would it be possible to extend the queue API to make this a bit nicer?

**Comment by selwin** [comment]
https://github.com/nvie/rq/pull/415 allows you to pass in your own `id` to `enqueue` or `enqueue_call` so I'm closing this as fixed.

**Comment by matthewcornell** [comment]
Hi. I'm a new RQ user - thanks! - and I have the same scenario, i.e., needing a job_id to save into a Django model. Given the ability to specify a job_id, how does one get a unique one, given concurrency, etc? I'm assuming duplicate ids is bad.

**Comment by samuelcolvin** [comment]
That should work. 

You might find the discussion on #678 relevant.
