### ISSUE TITLE
Making job timeout apply to entire Job life-span?

### ISSUE THREAD

**Issue by SirScott** [nvie/rq#396]
The behavior of setting a timeout on a Job seems only to apply when the function is being executed:  https://github.com/nvie/rq/blob/master/rq/worker.py#L487

However, in my opinion, the timer should effectively start at `job.enqueued_at`.  If `timeout=1` and it takes a day before a worker pulls it off of the queue, it seems that it should be considered a failure (even if the actual execution of the work takes < 1 second!).

Would you consider perhaps either modifying the existing `timeout` argument to span the full life of a Job, or allowing another parameter that controls a timeout between when a job is enqueued and when it is finally pulled from the queue and work can proceed?  Something along the lines of `begin_work_timeout`?  Or, is there already a way to get the behavior that I'm after?

**Comment by selwin** [comment]
This is fixed in https://github.com/nvie/rq/pull/453
