### ISSUE TITLE
New RQ CLI tool design

### ISSUE THREAD

**Issue by zhangliyong** [nvie/rq#400]
Interface
---------
Create a new CLI friendly `rq` command to support:

    $ rq --help
    Usage: rq [OPTIONS] COMMAND [ARGS]...

    Options:
      -u, --url TEXT  URL describing Redis connection details.
      --help          Show this message and exit.

    Commands:
      empty    [QUEUES]: queues to empty, default: failed...
      info     RQ command-line monitor.
      requeue  Requeue all failed jobs in failed queue

Use [click](http://click.pocoo.org) to implement.

**Comment by selwin** [comment]
This is already in master.
