### ISSUE TITLE
get_call_string UnicodeDecodeError in job.py

### ISSUE THREAD

**Issue by 7wonders** [nvie/rq#405]
using django_rq and some of my models return foreign chars which arent being handled nicely in the string representation get_call_string. Probably something I should fix on my django side but its worth doing some extra checking in get_call_sting too.

        arg_list = [repr(arg).decode('utf-8') for arg in self.args]
        arg_list += [u'%s=%r' % (k.decode('utf-8'), v.decode('utf-8')) for k, v in self.kwargs.items()]
        args = u', '.join(arg_list)
        return u'%s(%s)' % (self.func_name, args)

**Comment by dwaynebailey** [comment]
This is fixed with #492
