### ISSUE TITLE
TypeError: can't pickle instancemethod objects

### ISSUE THREAD

**Issue by timophey-nakhai** [nvie/rq#430]
Hello
I have a problem that i cant understand
My code:
from my_module.qw import my_func, my_next

redis_conn = Redis()
q1 = Queue(connection=redis_conn)
q2 = Queue(connection=redis_conn)

from os.path import dirname
sys.path.append(dirname(**file**))

job = q1.enqueue(my_func)
q2.enqueue(my_next, job, depends_on=job)

when i run it it gives me exception. I want to use 2 queues to build callback system
when the first task is ready its automatically calls the next function with result of the first function. What i 'am doing wrong?

**Comment by dsjoerg** [comment]
What was the exception?   (2.5 years later, I know...)

**Comment by selwin** [comment]
Instance methods can't be reliable pickled, so we won't be supporting this.
