### ISSUE TITLE
error No module named __restricted__

### ISSUE THREAD

**Issue by trollius** [nvie/rq#432]
Hello, 
I am having an issue with RQ. I have a queue with a simple task (2+3). But when I launch it, I have  following error (even though the module __restricted__ is installed and I can easily import it in python). 
---------------------
from redis import Redis
from rq import Queue
q = Queue(connection=Redis())
import time
from queue import q
def add(x, y):
    return x + y
def queue_test():
    queue = q.enqueue(add, 2, 3)
    time.sleep(3)
    return queue
----------------------

------------ error ---------
rqworker
13:18:13 RQ worker started, version 0.4.6
13:18:13
13:18:13 *** Listening on default...
13:18:28 default: __restricted__.add(2, 3) (70b50ebd-21d3-4015-a3ab-c3f53a5809db)
13:18:28 ImportError: No module named __restricted__
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/rq/worker.py", line 479, in perform_job
    rv = job.perform()
  File "/usr/lib/python2.6/site-packages/rq/job.py", line 466, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/python2.6/site-packages/rq/job.py", line 190, in func
    return import_attribute(self.func_name)
  File "/usr/lib/python2.6/site-packages/rq/utils.py", line 175, in import_attribute
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.6/site-packages/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named __restricted__

What might be causing this issue?

Thanks 
Anna

**Comment by selwin** [comment]
`rqworker` script couldn't import `restricted` module used in your app. You can specify `rqworker`'s import path using the `--path` variable.
