### ISSUE TITLE
How to delete the job from redis when the task is finished?

### ISSUE THREAD

**Issue by rochacbruno** [nvie/rq#439]
Hi,

As my jobs are finished, it keeps accumulating a huge number of job: entries on redis. How to delete them on job finishing? or how to write a script to periodically remove finished jobs?

Thanks

**Comment by selwin** [comment]
Besides what @psihonavt said, you can also do something like (be careful doing this on production database though):
```python
job_ids = redis.keys('rq:job*')
for job_id in job_ids:
    job = Job.fetch(job_id, connection=redis)
    # Check job status and delete if needed
```

**Comment by marcinn** [comment]
Hi @selwin. Your snippet has small issue. You're not fetching job ids from `redis.keys()` but key names. So every call for `Job.fetch` would give a `NoSuchJob` error, which may not be true.  

```
keys = redis.keys('rq:job*')
for key in keys:
    job_id = key.split('rq:job:')[1]
    job = Job.fetch(job_id, connection=redis)
    # Check job status and delete if needed
    redis.delete(key)  # <--- key, not job_id
```
