### ISSUE TITLE
async option requires redis connection

### ISSUE THREAD

**Issue by ivirabyan** [nvie/rq#448]
The docs say that `async` option is similar to `ALWAYS_EAGER` in Celery, and that this is useful for testing purposes. But when you use such option in Celery, it doesn't require a working redis server.
Why do we need a redis connection if we really bypassing workers?

**Comment by selwin** [comment]
Hi there, it's because we still need to store the result, job status and other metadata in Redis. Bypassing this during testing is not a good idea, in my opinion.

**Comment by wooyek** [comment]
Is there a way to truly simulate `ALWAYS_EAGER ` celery setting? When developing on Windows it's a pain to setup Redis, just to store a throwaway results.

**Comment by selwin** [comment]
See my answer abovw. If you don't want to setup Redis, you can use FakeRedis.
