### ISSUE TITLE
Problem with standard queuei case of duplicate jobs.

### ISSUE THREAD

**Issue by pranjal5215** [nvie/rq#449]
This is more of a feature/enhancement.

Lets assume there are multiple creators of tasks. My use case is; among 100 tasks created to be en-queued only 10-20 would be unique. With such a case getting 100 jobs en-queued in a standard queue is wasting resources. 
Ways to deal with problem are
1) Have each worker en-queue in standard queue and have each worker cache the response; so another worker would always check to see if result is present in cache before processing.
2) While en-queuing maintain a cache to check if job key is already present in queue

However, problem with both approaches is wasting resources for maintaining duplicate job keys.

Would It not make sense to have a hash/map instead of queue(configurable) such that every time result to be computed is updated even when its present in map or created (something like create_or_update) and then have a standard worker process normally.

Does something like this make sense with rq ?

**Comment by selwin** [comment]
I do understand the use case, but for now I think it would be better to implement this outside of RQ's core library unless there's a lot of demand for this feature. I think this can be easily implemented by subclassing `Queue` and overriding `enqueue_call`.
