### ISSUE TITLE
Work horses die because of `requests`

### ISSUE THREAD

**Issue by ducu** [nvie/rq#473]
Hey guys, here's a nasty bug which was very difficult to reproduce.

I've put up a gist (https://gist.github.com/ducu/ee8c0b1028775df6c72e) for your convenience but still it's quite tricky. Here's what's happening.

When the `requests` package is used in both the worker script (see "performance notes" section here - http://python-rq.org/docs/workers/) and the job as well (I've given the `count_words_at_url` example), it may become unusable in some circumstances. 

```python
import requests
 
def count_words_at_url(url):
    resp = requests.get(url, timeout=3)
    return len(resp.text.split())

def custom_worker():
    # using requests before forking causes the problem
    count_words_at_url('http://python-rq.org/') # commenting this line avoids the issue
 
    with Connection():
        q = Queue('test')
        w = Worker([q])
        w.work()
```

The only case I managed to reproduce (though it may happen in other cases) is when the network goes down for a while (unplug the cable or `sudo ifconfig en0 down`). When this happens, `requests.get` raises the `ConnectionError` for few jobs, then suddenly becomes unusable so when the next job tries to perform a request, the (work horse) process gets killed instantly. There is no exception anymore and from that moment on the jobs are left in the **started** status. The worker doesn't recover and it keeps on running in this way messing up the pending jobs until it gets shut down.

There seem to be two problems here. One is that `requests` doesn't work properly in multiple processes (main worker process and the forked job processes), and I'll report this on their repository.
But also an `rq` worker script problem which loses those killed work horses and messes up all pending jobs. Using `rqworker` doesn't cause this issue, so it's the way that `requests` works in forked processes that causes the problem.

Please let me know if I can help you reproduce the issue, and hopefully somebody more knowledgeable in the inner workings of `rq` is willing to tackle the problem. Cheers

**Comment by ducu** [comment]
You can follow the issue on the `requests` side as well: https://github.com/kennethreitz/requests/issues/2406

**Comment by selwin** [comment]
Sorry for the late response. So am I right in saying that the parent process doesn't currently detect if a child process dies unexpectedly?

**Comment by ducu** [comment]
Yes you're right

**Comment by selwin** [comment]
Closing this in favor of https://github.com/nvie/rq/issues/702 , @spiliopoulos is working on a patch for this.

**Comment by dflatow** [comment]
Hey guys, @selwin @ducu  

I've got an issue related to this (i think). But it's actually really easy to replicate. When making a request from a worker fails, the worker just dies, but no errors are reported nor is the job sent to the failed queue. 

my example:
```
def make_request():
    print "making response"
    response = requests.get("https://some.madeup.url")
    print "got response"

if __name__ == "__main__":
    make_request()
```
When I queue ```make_request``` the process just quits when making the request. Whereas a traceback is thrown when I execute the script directs. Took me a while to track this down, is there a fix or something I may be doing wrong?

**Comment by ducu** [comment]
Hey if I remember correctly I traced this down to a urllib3 issue, also
mentioned it on `requests`. But I've got no resolution to it sorry

**Comment by spiliopoulos** [comment]
Two separate issues work in tandem to create your problem.
1) Something is killing your python processes when you run your code in multiple rq processes. If I had to guess you try to get more than your system allows from some kind of resource (probably sockets so check your ulimit).

2) rq is not handling properly the case of the python process of a worker (specifically the workhorse) being killed. I have already created a pr #710  for a patch that fixes this. I'll guess it will probably get merged in the following days/weeks.

**Comment by selwin** [comment]
What @spiliopoulos said is correct. We can't really do anything about number 1, but we should report jobs that get killed unexpectedly.

Will try to find some time to do another review of #710 this weekend and hopefully merge that in. It changes the way we monitor jobs so I want to make sure that it works properly.

**Comment by robmcdan** [comment]
I was having this trouble -- work horse dies abruptly in requests. It repro'd only when forked from rq workers (worked fine when run standalone). I was able to debug the issue to  _get_proxy_settings in _scproxy which crashes.

In my case, this solved my problem: https://bugs.python.org/issue24273
