### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by robodude666** [nvie/rq#474]
Not particularly an issue with `rq` itself, but is there a planned release soon? There's been a lot of incredible changes over the last half a year.

@nvie @selwin Might be nice to determine what's needed in order to make master releasable, update docs, and tell the world about it.

**Comment by selwin** [comment]
Agreed, we already have a good number of new features for the upcoming 0.5 release. I'd just like to get https://github.com/nvie/rq/pull/475 merged in before we tag the next release.

**Comment by selwin** [comment]
I just documented some of the major feature changes in 0.5.0 in this commit: https://github.com/nvie/rq/commit/008d72ff09e77e8186b81955ebac9509fd85b701

We'll need @nvie's help to tag the release and push it to PyPI though.

**Comment by nvie** [comment]
I just released `master` as 0.5.0. Thanks for all the hard work, and driving this release, @selwin! Awesome job :)
