### ISSUE TITLE
get_current_task() returns None while task is running

### ISSUE THREAD

**Issue by simongray** [nvie/rq#476]
Using Python version 3.4.2 and rq version 0.4.6.

After enqueueing a simple long running task I would expect get_current_job() to return something other than None while the task is running, yet it doesn't. Maybe there is  something wrong with my understanding of what get_current_job() is supposed to do?

Here's some test code to replicate the issue

```python
def long_running_task():
    n = 0
    while n < 120:
        n += 1
        time.sleep(1)
```

```python
q = Queue(connection=Redis())
q.enqueue(long_running_task)
```

I have verified in the RQ output that the task is indeed running (no return yet) and any calls to ```get_current_job(connection=Redis())``` simply return None.

**Comment by nvie** [comment]
It does not return anything outside of a job function. Only _within_ a running job function's body itself (i.e. _inside_ your `long_running_task`) there's a notion of the current task. RQ does not provide control structures that allow you to know what other processes are currently running. (And it won't in the future.)
