### ISSUE TITLE
Run task fovever

### ISSUE THREAD

**Issue by raelmax** [nvie/rq#484]
Hi,

I need run a task(redis pubsub listen) forever but rq move it to failed queue after timeout, how can i set my task to not expire?

**Comment by selwin** [comment]
Hi there, you can set really long job timeouts but I don't think a pubsub job is a suitable use case for RQ (in general).

**Comment by raelmax** [comment]
Hi, you are right. I make some changes in my app and i see that rq is not to this use case. Thanks!
