### ISSUE TITLE
Worker fails during adding new dependency to a current job

### ISSUE THREAD

**Issue by ta2-1** [nvie/rq#487]
I tried to test what can happen if current job is added as dependency to a new job and it finishes before `pipe.execute()` here (https://github.com/nvie/rq/blob/master/rq/queue.py#L205).
Deferred set and set of dependents for a current job are filled and deferred job is created in any case. 
If current job finishes before `pipe.execute()` then worker fails to enqueue dependents for this job:

```
rq.exceptions.NoSuchJobError: Unexpected job format: {'status': 'deferred'}
```

If I add `pipe.multi()` after `pipe.watch()` then it seems that everything works. Probably it has been missed there.

**Comment by selwin** [comment]
Yes, you're right. The [example](https://github.com/andymccurdy/redis-py#pipelines) in redis-py's documentation also shows the `watch` command being used in conjunction with `multi`. Mind opening a PR for this?
