### ISSUE TITLE
Set Dependency on Job Timeout/Expire

### ISSUE THREAD

**Issue by robodude666** [nvie/rq#488]
I think it would be useful to be able to set a job's dependency as the Timeout or TLL of another job.

For example:
- Queue Job A with 100 second timeout & no TTL.
- Queue Job B with a dependency of Job A's timeout/TTL.

If Job A completes within 100 secs it will simply be "finished." Since it has no TTL time, the TTL dependency will trigger instantly causing Job B to run. If Job A takes over 100 sec to complete it will trigger Job B to run. It could also be useful to specify the dependency on being for only the Timeout, only the TTL, or both.

This will mostly be useful if you want to cleanup after a Job, whether it was successful or failed. Similarly, it would be useful to queue based on a job failing -- but I know we've had that fun discussion before :).

**Comment by selwin** [comment]
Sorry, but I'm not to keen on making RQ's dependency management more complex.

To handle job failure cleanups, @bradleyy 's [pull request](https://github.com/nvie/rq/pull/446) is the right approach in my opinion. It would be good if you can help getting that PR ready for merging.

I also though about whether we should introduce `success_handlers`, similar to `exception_handlers`, although cleanup jobs could also be performed by subclassing `Worker`.
