### ISSUE TITLE
Log raise error when job's return value is not ascii

### ISSUE THREAD

**Issue by phith0n** [nvie/rq#493]
In python 2.7，My job  is to get a webpage whose characters are not all english，so the log raise error：
“UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)”
![qq20150224-1 2x](https://cloud.githubusercontent.com/assets/5711185/6349665/c252cd7c-bc67-11e4-9077-782bc918a8a8.png)

**Comment by selwin** [comment]
Could you try if this is still an issue in the current master? We merged this PR in yesterday: https://github.com/nvie/rq/pull/492

**Comment by phith0n** [comment]
My problem seems to have not been resolved.
In worker.py line 572:

```
        if rv is None:
            self.log.info('Job OK')
        else:
            self.log.info('Job OK, result = %s' % (yellow(text_type(rv)),))
```

rv is result of my job, if it's a non-ascii text, rqworker will raise an error.

**Comment by Rvthof** [comment]
Was there any more followup on this?
I'm running into the same issue, even if I run something like this:

**Comment by selwin** [comment]
@Rvthof can you please test whether it still fails after this commit? https://github.com/nvie/rq/commit/2140cc4fab59ed121e8f07c5ef5eabed132c59bd

**Comment by selwin** [comment]
@Rvthof whoops, I meant this one: https://github.com/nvie/rq/commit/544f2e6fb2ca6f8ff94a5e288408fb85d330c555

**Comment by Rvthof** [comment]
My apologies, it seems the issue stemmed from having a woefully out of date version of redis.
