### ISSUE TITLE
@job decorator does not work!

### ISSUE THREAD

**Issue by knightsamar** [nvie/rq#503]
Using the ``@job`` decorator example specified in the documentation http://python-rq.org/docs/, I tried the following code:

```
from redis import Redis
from rq.decorators import job
import time

rc = Redis() #create redis connection for the queue

@job('low', connection = rc, timeout = 5)
def sumup(x, y):
    return x + y

job = sumup.delay(4, 2)
time.sleep(1)
print job.result
```

The ``sumup`` function always returns **None** and the job also doesn't appear to be enqueued for worker started using ``rq worker```.

version: 0.5.0

**Comment by selwin** [comment]
You should run the task (normally done by `rqworker`) before asking for the result:
```python
job = sumup.delay(4, 2)
job.perform()
print job.result
```
