### ISSUE TITLE
Jobs on Failed Queue with status Started

### ISSUE THREAD

**Issue by gracaninja** [nvie/rq#509]
Hello,

I am having some jobs landing on the failed queue with status started, example:

ID:ac4f53df-2591-46f4-bcdb-5d652acb49eb
Queue:default
Timeout:600
Result TTL:None
Created:16 de Março de 2015 às 23:03
Queued:16 de Março de 2015 às 23:03
Status:started
Callable:apps.translation_pipeline.models.job.update_job_linguist_review_time
Args:
Kwargs:
Exception:

I am not sure what the status started means and how I can fix this problem. It seems that if I requeue the job then everything goes well.

- What does this status mean?
- Should I make a background job that checks for all jobs on this status and just requeues them?

Thanks in advance,

João

**Comment by selwin** [comment]
Jobs in the failed queue should have `failed` as status so what you reported sounds like a bug. Can you reliably reproduce this?

**Comment by gracaninja** [comment]
The main problem is that it is non deterministic. Sometimes some jobs get to the failed queue on that status and if I enqueue them again they work fine. I get a couple of them every day from different functions. But haven't found a way to reproduce them.

**Comment by gracaninja** [comment]
Today I had around 40 jobs on that state again. I basically run a script that enqueues a job for each user. Some of the users go to the fail queue with the task started. But it's not deterministic. Can this be related with some sort of timeouts?

**Comment by selwin** [comment]
Hmm, to test if this is related to timeouts, can you try increasing the job timeout to a high number and see if this still happens?

**Comment by gracaninja** [comment]
I was able to reproduce the error. If I stop a worker (like heroku does everytime we deploy) the running workers are killed and moved to the failed queue with status started. 
All I have to do is to requeue them and things work properly.

**Comment by selwin** [comment]
Ah I see, yes it's a bug. When the jobs get moved to Failed Queue, we should also change the status to failed.
