### ISSUE TITLE
Implementing a serial queue

### ISSUE THREAD

**Issue by ydaniv** [nvie/rq#511]
If I'm not mistaken, this could be achieved using current API like combining `get_jobs()` and job dependency to always get the last job in queque and make it the dependency for the next one to enqueue.
However, it would be nice to have that sugar anyway.

**Comment by selwin** [comment]
Sorry but I'm not entirely sure what you mean by "serial queue". Care to elaborate?

**Comment by ydaniv** [comment]
See [here](https://github.com/bretth/django-pq#serial-queues).

My use case is to offload non-thread-safe operations to a queue which will be consumed in a serial manner, which will solve concurrency issues.

**Comment by nvie** [comment]
If you want this behaviour, you could dedicate a specific queue for this (e.g. name it 'serial'), then have it consumed by only a single worker, or am I missing something?

**Comment by nvie** [comment]
There are many use cases of a queue, and I can totally see that locking the entire queue for reads temporarily is a valid use case, but RQ can never support all use cases, and this seems too specific to land in RQ natively. As mentioned in the previous comment, I think you can use existing constructs to enable this behaviour (or place your locks manually outside of RQ entirely).

**Comment by ydaniv** [comment]
Hmmm... OK, cool. I thought the parallel behavior would render this more tricky then it seems. Thanks!
