### ISSUE TITLE
depends_on job queue always used

### ISSUE THREAD

**Issue by caseyjlaw** [nvie/rq#512]
When submitting a job with a dependency, the queue of the dependency seems to always be used. For example:

    with Connection():
        q = Queue('high')
        jobh = q.enqueue_call(func, args)
        q = Queue('low')
        jobl = q.enqueue_call(func, args, depends_on=jobh)

In my small tests, the 'jobl' is submitted to the 'high' queue. I am somewhat new to rq, but that behavior was unexpected.

**Comment by caseyjlaw** [comment]
Sorry, I just saw that this issue is well known (https://github.com/nvie/rq/issues/387). Closing...

**Comment by selwin** [comment]
I'm reopening this as we now have the building blocks in place to allow job dependency to be used across different queues (in the same Redis DB).

**Comment by caseyjlaw** [comment]
Nice to hear! Let me know if I can help.
  Do I understand correctly that using multiple Redis DBs and connections would get around this issue? For example, the following should work?
    with Connection(Redis('localhost', 6379)):
        q = Queue('high')
        jobh = q.enqueue_call(func, args)
        with Connection(Redis('localhost', 6380)):
            q = Queue('low')
            jobl = q.enqueue_call(func, args, depends_on=jobh)

**Comment by caseyjlaw** [comment]
Nice to hear! Let me know if I can help.
Do I understand correctly that using multiple Redis DBs and connections would get around this issue? For example, the following should work?

    with Connection(Redis('localhost', 6379)):
        q = Queue('high')
        jobh = q.enqueue_call(func, args)
        with Connection(Redis('localhost', 6380)):
            q = Queue('low')
            jobl = q.enqueue_call(func, args, depends_on=jobh)

**Comment by selwin** [comment]
No, it will not work on different Redis DBs.

**Comment by jlopex** [comment]
@selwin any chance to look at the PR I proposed?

**Comment by jlopex** [comment]
@selwin Should we close this?
