### ISSUE TITLE
suggestion: distributed job dependencies

### ISSUE THREAD

**Issue by Fkawala** [nvie/rq#518]
Hello, 

I'm wondering if it is sensible / doable to distribute the job dependency handling among the workers. A minimal example of this feature described below.

- A worker named **w** does the job named __x__ which is the prerequisite of a job named __y__.
- Afterwards, when **w** notifies of the termination of __x__, **w** enqueues __y__.

The typical use case is when the process that enqueued jobs does not use the outputs of the jobs. In such a situation, the process has to be kept alive solely to handle the dependencies. 

best,
f.

**Comment by selwin** [comment]
This is already supported. You can use `depends_on` kwarg when calling `queue.enqueue()`. More info on http://python-rq.org/docs/
