### ISSUE TITLE
rq scripts gone from RQ repo?

### ISSUE THREAD

**Issue by ggold6** [nvie/rq#520]
Guys, what happened to all the scripts in the RQ repo? I'm using the excellent rq-gevent-worker library which imports rqworker.py from rq.scripts. But the scripts folder has been emptied. 

Is this an 'issue' or there's a different way of setting up things- any word here?

**Comment by selwin** [comment]
Hi there, the scripts have been moved to https://github.com/nvie/rq/blob/master/rq/cli/cli.py so you'll need to modify your library.
