### ISSUE TITLE
Job cleanup respects only ttl and not result_ttl

### ISSUE THREAD

**Issue by ryanisnan** [nvie/rq#521]
I may be mistaken here, but in looking at the `Job.cleanup` method, Jobs only respect the `ttl` property when expiring job information, and ignore `result_ttl`.

Here's a note on the most relevant commit.

https://github.com/nvie/rq/commit/85e9014296be602ad27c3bf8168ff9b7ddfb3aa6#diff-fd5a0b7287d0181491e122928e1c56c6R370

**Comment by selwin** [comment]
Closed as this is not a bug. See [this explanation](https://github.com/nvie/rq/commit/85e9014296be602ad27c3bf8168ff9b7ddfb3aa6#commitcomment-10953837)
