### ISSUE TITLE
What's the function "self.func(*self.args, **self.kwargs)" in job.py?

### ISSUE THREAD

**Issue by Uventus** [nvie/rq#522]
What's the function "self.func(*self.args, **self.kwargs)" in job.py?

    # Job execution
    def perform(self):  # noqa
        """Invokes the job function with the job arguments."""
        self.connection.persist(self.key)
        self.ttl = -1
        _job_stack.push(self.id)
        try:
            self._result = self.func(*self.args, **self.kwargs)
        finally:
            assert self.id == _job_stack.pop()
        return self._result

**Comment by nvie** [comment]
This helper property gets the actual function (a Python object) from the function description that the Job encodes. See https://github.com/nvie/rq/blob/master/rq/job.py#L197-L206
