### ISSUE TITLE
Allow setting meta in enqueue_call

### ISSUE THREAD

**Issue by johtso** [nvie/rq#528]
It would be rather convenient to be able to define job meta information in a keyword argument to `enqueue_call`, unless I'm missing something and it's already possible!

**Comment by selwin** [comment]
Yes, ai think this is a reasonable request. Feel free to open a PR for this.

**Comment by johtso** [comment]
Good stuff, I'll see if I can put something together.

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/609
