### ISSUE TITLE
How can I get all job ids that are either enqueued or started?

### ISSUE THREAD

**Issue by johtso** [nvie/rq#532]
My current setup is to have database entries that can be marked as "dirty", and to have a separate process that schedules the relevant jobs to update those entries (one job per entry).

Once the job finishes, it updates the entry and marks it as "clean" up to that point in time.

What I want to do is compare the dirty entry ids with all existing jobs, and only create new jobs if necessary.

I only see a way to get all jobs that are on the queue, but while they are being executed they become invisible.

Is there a way get the ids of all jobs either queued or being executed?

**Comment by johtso** [comment]
I've just found the `StartedJobsRegistry`, which when combined with `queue.jobs` gets me what I want.

Would this be something that would make sense to expose is a friendlier way?

**Comment by joostdevries** [comment]
@johtso maybe it's just my opinion but in general I would avoid having to take stuff out of a queue on a regular basis.

**Comment by selwin** [comment]
I do plan on document and explain the concept behind job registries so people can more easily build or script monitoring tools for RQ.

But yes, I do recommend against manipulating large queues as they are generally expensive operations.
