### ISSUE TITLE
use flask to add job to rq 

### ISSUE THREAD

**Issue by baxiaoshi** [nvie/rq#537]
i write a flask application, but when I write a job to  add redis use enqueue_call
![image](https://cloud.githubusercontent.com/assets/11749031/7834540/da02ee92-04a2-11e5-9880-a93b1592b730.png)
this enqueue_call auto add app.job.views，but not my function

**Comment by selwin** [comment]
From the screenshot you provided, it seems like the worker was not able to import app.job.views. Please make sure your worker's `PATH` is correctly setup (your worker script should be able to import `app.job.views.ansible_run`).

I'm not a Flask user so I don't have any experience with running Flask based functions, but there seems to be a helper library for Flask: https://github.com/mattupstate/flask-rq

**Comment by baxiaoshi** [comment]
![image](https://cloud.githubusercontent.com/assets/11749031/7839814/04feb008-04c7-11e5-8d8e-314cd0731dcb.png)
I find this problem because it think   this is  inspect.isfunction(func) or inspect.isbuiltin(func)

**Comment by selwin** [comment]
From the stack trace you provided, it's the import mechanism that triggered the error :)
