### ISSUE TITLE
Subclassing the worker for Flask

### ISSUE THREAD

**Issue by joostdevries** [nvie/rq#538]
We're integrating RQ into our Flask app and use the following code to have the flask app context around. I'm basically just curious whether this is a recommended pattern and whether it's something other people could use.

```python
class FlaskBoundWorker(Worker):
    def perform_job(self, job):
        with application.app_context():
            return super(FlaskBoundWorker, self).perform_job(job)
```

**Comment by selwin** [comment]
I think you could get away without having to subclass `Worker`, as long as you run the worker with Flask environments setup:
```python
with application.app_context():
    worker = Worker([queue])
    worker.work()
```
Could you please verify if the above snippet works? If it does, I'd like to document the easiest way to run Flask background jobs on http://python-rq.org .

With [django-rq](https://github.com/ui/django-rq), all you need to do is run `python manage.py rqworker`, I'd like it if there's a similar library for Flask. There's With [django-rq](https://github.com/ui/django-rq), all you need to do is run `python manage.py rqworker`. There's [flask-rq](https://github.com/mattupstate/flask-rq) but the last commit in that repo was in 2013 so I'm not sure whether it still works.

**Comment by joostdevries** [comment]
@selwin The reason I'm subclassing is because I use SQLAlchemy have that configured to clean up the session when tearing down the context (http://flask.pocoo.org/docs/0.10/patterns/sqlalchemy/). This makes sure no models stay in memory between (web) requests. I'd like the same behavior for every job, so creating a fresh context for every job looks sensible.

**Comment by joostdevries** [comment]
@selwin fyi: emailed the maintainer of flask-rq to check if I can help out.

**Comment by joostdevries** [comment]
@selwin I just had contact with Matt and I can now work on the repo. I'll try to get some work done the coming days/weeks.

**Comment by selwin** [comment]
Great, let me know how it goes. If it works well, I can add a link to `flask-rq` on python-rq.org just like I did for Django: http://python-rq.org/patterns/django/ . Thanks for helping.
