### ISSUE TITLE
Missing deps when installing on python2.6 with wheel

### ISSUE THREAD

**Issue by joostdevries** [nvie/rq#540]
I've got to provide `--no-use-wheel` to pip to make sure argparse and importlib are installed.

**Comment by selwin** [comment]
I'm not a packaging expert, but it seems like we need to define conditional dependencies: https://wheel.readthedocs.org/en/latest/#defining-conditional-dependencies

**Comment by selwin** [comment]
Should be fixed in https://github.com/nvie/rq/commit/efcdd15902677cee4307d8120faace25d7e4e3b1
