### ISSUE TITLE
Logging with multiple workers 

### ISSUE THREAD

**Issue by ta2-1** [nvie/rq#546]
When a job is performed `rq.worker` logger with `INFO` level prints something like this: 
```
[09/Jun/2015 03:50:54]	*** Listening on default...
[09/Jun/2015 03:50:54]	default: job_func(args) (job ID)
[09/Jun/2015 03:50:55]	Job OK
[09/Jun/2015 03:50:55]	Result is kept for 500 seconds.
```
There will be a messy if you have multiple workers running.
Is `rq.worker` logger intended for non-production using with a single worker only? 

I'm trying to create a clear logging system with multiple workers. The only idea is to have log references (via job IDs) where a job was added and retrieve the current job ID and paste it to every log message from the job.

```python
def job_func(*args)
    job = get_current_job()
    logger.info("Job %s started", job.id)
    ...
```

```python
def new_job():
    job = queue.enqueue(job_func, *args)
    logger.info("Job %s was added to the %s queue", job.id, queue.name)
    ...
```

Has anyone solved a similar issue?

**Comment by selwin** [comment]
Would it make more sense to add worker IDs to log messages? Another idea is to configure logging such that each worker logs to its own logfile.

**Comment by ta2-1** [comment]
@selwin thanks. I'll think about your ideas. And how to get a worker ID to add it to log messages from a job?

**Comment by selwin** [comment]
At the moment, all the logging is done by the worker itself so it can always access it's worker_key, right?

**Comment by NeckBeardPrince** [comment]
Has this been brought back up?

**Comment by selwin** [comment]
No, but you can always configure each worker to log to it's own file.
