### ISSUE TITLE
Reload job instance in exception handler

### ISSUE THREAD

**Issue by olingerc** [nvie/rq#547]
When jobs raise Exceptions, the exception handler gets the job instance as it was at the time it was enqueued.
In my case I would like to access meta data that was added during job execution in the handler. Would you accept a PR that simply calls job.reload() at the beginning of the handler?

**Comment by selwin** [comment]
I'd rather not incur an additional Redis call when jobs failed, considering the default exception handler doesn't do anything with it (and I'd imagine that's the default behavior). You should call `job.reload()` in your custom exception handler instead.

Using custom exception handlers should also be much easier when https://github.com/nvie/rq/pull/557 is merged.
