### ISSUE TITLE
perform_job leaves worker current_job set after exception handling

### ISSUE THREAD

**Issue by grzaks** [nvie/rq#558]
The workers `perform_job` function has the `try ... catch ...` block for exception handling but when the job function throws an exception the `self.set_current_job_id(None, pipeline=pipeline)` is never called. 

This leaves the worker in weird state where it's waiting for new job but still has `current_job` ID set in redis.

The `set_current_job_id(None, ...)` should be either in the `catch` or `finally` block IMHO.

https://github.com/nvie/rq/blob/master/rq/worker.py#L564

**Comment by selwin** [comment]
Yeah, sounds like a bug to me. Pull request welcome :)

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/637
