### ISSUE TITLE
Error after update to raven 5.4.0

### ISSUE THREAD

**Issue by ldath** [nvie/rq#559]
I have error:
AttributeError: 'Client' object has no attribute 'servers' in file ".../site-packages/rq/contrib/sentry.py", line 15, in register_sentry

**Comment by selwin** [comment]
PR to fix this welcome :). Alternatively, you can log errors to `sentry` using RQ's logging mechanism.

**Comment by nvie** [comment]
I've fixed this bug in 28a19ee71782bffa5f850513fc1c2a5234686a49. Docs are updated in d4890077fef613e311ff55d5200b7b6a209bbb19.

**Comment by nvie** [comment]
Released to PyPI as rq==0.5.4 just now — please upgrade and let me know how it works.
