### ISSUE TITLE
custom exception handler never gets called when Redis connection is lost

### ISSUE THREAD

**Issue by jlopex** [nvie/rq#562]
This issue happens when Redis connection is lost, you can duplicate by shutting down the redis server while a Job is being executed.

Then, when the job finishes, worker.py:perform_job() will raise an Exception. This exception will be handled by the generic except clause.

Within this except clause, RQ tries to update the status and the started_job_registry, but as there's no connection with the redis server, pipeline.execute() call will raise a new redis.exceptions.ConnectionError.

This new Exception is not allowing RQ to execute any custom exception handler.

Should we call the custom exception handlers before trying to update the Redis server data?

**Comment by selwin** [comment]
I think we should update the job data first before calling custom exception handlers. However, I do agree that custom exception handlers should still be called if we can't write to Redis. Could you please make a PR for this?
