### ISSUE TITLE
dependent jobs aren't enqueued on the correct queue

### ISSUE THREAD

**Issue by jlopex** [nvie/rq#563]
After a few attempts I noticed that dependent jobs are always inserted on the first job queue.

Find attached a quick example to reproduce the issue:

```
q = Queue('worker_1')
first_job = q.enqueue(first_step)
q = Queue('worker_2')
q.enqueue(second_step, depends_on=first_job)
```

When first_step finishes, second_step is enqueued at "worker_1" queue instead of "worker_2" queue.

**Comment by olingerc** [comment]
Would this be the same as #512?

**Comment by jlopex** [comment]
@olingerc yes, it seems to me to be the same issue, sorry for the duplicate.

Should I update the PR to reference the oldest issue?
