### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hugorodgerbrown** [nvie/rq#575]
Hi there - not sure how to raise this - it's not an "issue" as such - but I was wondering whether a new version would be cut / pushed to PyPI any time soon. We really need the async job fix, and just need to know whether to wait for an official version, or to link to the Githib commit directly?

**Comment by selwin** [comment]
If possible, I'd like to get these two fixes in the next version: https://github.com/nvie/rq/pull/564 and https://github.com/nvie/rq/pull/560

**Comment by jlopex** [comment]
@selwin could it be possible to make a release with the #564 changes?

**Comment by selwin** [comment]
Please give me a few days, I'd like to resolve this issue: https://github.com/nvie/rq/issues/514

**Comment by jlopex** [comment]
Hey @selwin, any updates about the upcoming release?

Thanks!

**Comment by selwin** [comment]
@nvie can you please make a 0.5.6 release on PyPI? I updated the changelog in this commit: https://github.com/nvie/rq/commit/c2f452c47aadb6033d33650efdcadc8eeb82186c

**Comment by nvie** [comment]
Hi @selwin, sure, I just released 0.5.6 to PyPI. Thanks again for driving this release! I have all my unread issue/PR notifications archived for a rainy day, and I'll probably batch-process through them when I find the time.

**Comment by selwin** [comment]
Thanks!

**Comment by hugorodgerbrown** [comment]
Thanks @selwin and @nvie
