### ISSUE TITLE
Output to file

### ISSUE THREAD

**Issue by cyberlake** [nvie/rq#579]
Is there any way to redirect worker outputs to file? I want to start multiple workers with multiprocessing using below code and I want workers to output to worker specific files.

```python
def run_worker():
    listen = ['some_list']
    with Connection(redis_conn.connection):
            worker_csv = Worker(map(Queue, listen))
            worker_csv.work()

def start_multiple_workers(num_of_workers):
    with open('pids', 'w') as fid:
        fid.write("")

    for i in range(0, int(num_of_workers)):
        p = Process(target=run_worker)
        p.start()
        with open('pids', 'a') as fid:
            fid.write(str(p.pid) + '\n')
```

I tried to change `sys.stdout` but it didn't help. Didn't find anything relative in documents as well. Is this kind of feature supported in current version? If yes, can you please tell how?

**Comment by jlopex** [comment]
I'm doing this using supervisor on top of my workers.

Check this out:

http://python-rq.org/patterns/supervisor/

**Comment by jlopex** [comment]
@cyberlake you can also achieve this by overwritting the 'rq.worker' logging configuration.

But if you need to launch multiple workers and log their output I recommend you using supervisor.

**Comment by selwin** [comment]
Like @jlopex mentioned, logging is the best way to do so.
