### ISSUE TITLE
noobs attempt to use simpleworker

### ISSUE THREAD

**Issue by jeremy-rutman** [nvie/rq#583]
I'd like to use SimpleWorker to avoid forking
I can't quite figure out how to start a simpleworker  - from a python module I tried

    sworker = SimpleWorker
    sworker.work

but this didn't seem to do it , and from command line I am not clear on what goes after the -w option
    rqworker -w  [what goes here]

**Comment by selwin** [comment]
"rqworker -w rq.worker.SimpleWorker" should work.

**Comment by jeremy-rutman** [comment]
thanks that did it.  It seems like i need to modify Job also (I am creating matlab engines in worker.__init__ and need to pass them into the job , so I added a job.matlab_engine variable and in Job.perform I tack that onto the end of args* ) So is there some easy way to specify my own job , or should I specify an alternate class of my  - or best of all is there a convenient place to get at the *args and **kwargs for this ? The *args and **kwargs in SimpleWorker are not the actual arguments going to the job- if they were, that would be perfect for my purposes

**Comment by selwin** [comment]
Yeah, you can use `rqworker --job-class="path.to.my.JobClass"` for this. You can also specify your own queue class to use so you can get creative with your solutions.

**Comment by jeremy-rutman** [comment]
ok i got something working without modifying job.py  -  in my simpleworker subclass I can see job._args, so I added my engine there and it works great.

**Comment by jeremy-rutman** [comment]
is there some known behavior where if you specify a worker other than the standard one, some jobs never get onto the queue? my modified worker works fine when it gets a job, but some jobs never seem to get picked up after i call q.enqueue - they don;t show up on the web monitor and the workers remaimn listening.  I didn't modify anything other than to add my   modified_worker.py to the /usr/local/lib/python2.7/dist-packages/rq/  directory

**Comment by selwin** [comment]
Well, whether custom workers work reliably depends on the custom worker implementation itself, obviously :)

**Comment by jeremy-rutman** [comment]
the thing is the custom worker is not getting a job - the job does not make it onto the queue, according to the web interface (and debug lines in the worker which print msgs as soon as a job is rec'd) .  thus i don't beleive it has to do with the custom worker implementation
