### ISSUE TITLE
Supervisor and warmly shutting down workers

### ISSUE THREAD

**Issue by jredd** [nvie/rq#586]
I currently have my setup running several workers under Supervisor. It's great, but I'd like to be able to shut down a worker but have it finish it's job then deactivate itself. I'm willing to bet I'm doing this all wrong, but when I pass the sigint to the worker it just tanks any currently running job and leaves those workers as ghosts in the system...I then have to go flush redis to clear the junk out.

```python
with Connection():

    workers = Worker.all()

    for worker in workers:
        
        os.kill(worker.pid, signal.SIGINT)
```

**Comment by selwin** [comment]
I haven't personally used supervisor, but something similar to this should work: http://python-rq.org/patterns/supervisor/

**Comment by sisterdev** [comment]
So just linking to documentation that I've already read does not fix this issur

**Comment by jredd** [comment]
Sorry was logged into a different account. But yes, that documentation is what I used to setup rq workers under supervisor... So no help from that.

**Comment by nvie** [comment]
@jredd supervisord defaults to a 10 seconds time period after sending the stop signal before it sends a SIGKILL. If you job does not finish within 10 seconds, this may happen and then it behaves like you described. Have you tried setting `stopwaitsecs` in your supervisord.conf file to something high enough for your use case?

**Comment by aehlke** [comment]
@jredd did you figure out a good approach?

**Comment by jredd** [comment]
@aehlke I never found the time to really work it out. I had thought of using @nvie's suggestion to just turn up the timeout time to an amount I knew would be beyond the scope for the job duration time.

**Comment by KMouratidis** [comment]
For any future wanderers: 

It is a bit of a workaround but you could try working with `supervisorctl signal` which paired with auto-restart works as I would expect it to, e.g.: 

```
~$  supervisorctl -c myconf signal TERM prod-666
prod-666: signalled

~$  tail -f  worker.log
07:51:47 *** Listening on prod-666...
07:51:47 Cleaning registries for queue: prod-666
08:01:54 Cleaning registries for queue: prod-666
08:03:22 Warm shut down requested
08:04:05 Worker rq:worker:prod-666: started, version 1.5.2
08:04:05 *** Listening on prod-666...
08:04:05 Cleaning registries for queue: prod-666
```

Here's most of my config:
```
[program:prod-666]
command=/PYTHON_PATH/rqworker prod-666 <CUSTOM ARGS> --name prod-666
numprocs=1
autostart=true
autorestart=true
startretries=10
stopsignal=INT
stdout_logfile=/LOG_PATH/worker.log
stderr_logfile=/LOG_PATH/worker.err.log

[inet_http_server]
port=127.0.0.1:9001
username=<USERNAME>
password=<1234_is_not_super_secure>

[supervisord]
logfile=/LOG_PATH/supervisord.log
user=<MY_SYSTEM_USER>

[supervisorctl]
serverurl=http://127.0.0.1:9001
username=<USERNAME>
password=<1234_is_not_super_secure>

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
```
