### ISSUE TITLE
Is it possible to add queue to worker without worker restart?

### ISSUE THREAD

**Issue by kmadac** [nvie/rq#592]
Hello,

I would need to execute command by one of existing queues from remote system on the worker which should add new queue into the worker itself on-the-fly (without restart). Is something like this possible? 

I'm using official worker snippet to run my workers:

```
with Connection():
    qs = map(Queue, sys.argv[1:]) or [Queue()]

    w = Worker(qs)
    w.work()
```

As a workaround, it should be possible to achieve this by special worker which would restart appropriate workers OR execute function which sends SIGTERM to worker itself and let supervisor to start it again with new queue. But it'll be more elegant/cleaner way to add a queue without restart if possible.

**Comment by glenfant** [comment]
```w.work()``` is an infinite loop. So you can't add any queue to a running worker as long if I understand correctly.

I use to start the workers for all queues even those that have few activity.

**Comment by selwin** [comment]
This is not supported at the moment. You can workaround this by implementing your own system to notify the process manager (like supervisord) to restart the worker process.

**Comment by kmadac** [comment]
Thanks for the feedback. I will notify supervisord to restart workers.
