### ISSUE TITLE
UnpickleError: (u'Could not unpickle', ImportError('cannot import name SmsRecord',))

### ISSUE THREAD

**Issue by zt9** [nvie/rq#608]
I have been struggling with an import issue that I cannot seem to resolve.

I have a django app (not using django-rq because of some issues I do not remember) and have been using rq nicely for a while now. I added another module to my django app, and I started getting importError. I confirmed there are no circular import issues.  I suspect there is a problem in the namespace  and so want to explain a bit. I also feel like the error messages are not indicative of the real problems. 

I have a module called `quicken` module that has `from sprint.models import SmsRecord`. There were no problems. I later created a module called `waze` that also `from sprint.models import SmsRecord`, but now I get a `UnpickleError: (u'Could not unpickle', ImportError('cannot import name SmsRecord',))`. Here is the [full traceback](https://gist.github.com/zt9/a56c93ad19ad48e50448).

To see what is happening, I included a `import waze` in my [worker.py](https://gist.github.com/zt9/b02945ba26727b8f3c65) to see the cause of the error, and I see slightly better [error message without the unpickleError](https://gist.github.com/zt9/e31546189244445a0dc7). Any clues as to how I might debug this better?

Version used: rq==0.5.6, redis==2.10.5 and django==1.8.4 all in osx environment.

**Comment by selwin** [comment]
This doesn't seem to be a bug in RQ but in the way your environment is set up. I'm not familiar with the way your code is structured so I can't provide much insight.

**Comment by CoreyAR** [comment]
I encountered this same problem locally and was able to solve it by ensuring I was running `rq worker

**Comment by wroscoe** [comment]
upgrading to rq==0.10.0 fixed this error for me

**Comment by lifenautjoe** [comment]
Having this issue now on 1.1.0 😬

**Comment by paltman** [comment]
Looks like this exception was removed in https://github.com/rq/rq/commit/e1cbc3736c55d7a72be121a170d1b8c811619dc2#diff-27817b1a9be843cacb4ebeb20393c486
