### ISSUE TITLE
job refresh needed before changing the job status

### ISSUE THREAD

**Issue by tramora** [nvie/rq#610]
Shouldn't the job instance be refreshed before changing its end datetime and status on completion ?
in file **rq\worker.py** function **perform_job** :
<pre>
if result_ttl != 0:
                    self.log.debug('Need to refresh before saving status and datetime')
                    job.refresh()

                    job.ended_at = utcnow()
                    job._status = JobStatus.FINISHED
                    job.save(pipeline=pipeline)
</pre>

Otherwise it can lead to issue like the following

1. job A fails at its first run before the end of the process
2. job A is re-queued and changes the meta data at the end (this time successful)
3. job B which depends on A is started and expects a value in its ancestor meta data.
=> job B fails as the state of A in 1. (without the new value) is saved by the worker

**Comment by selwin** [comment]
RQ doesn't expect job metadata to be modified during it's time of execution. If you have an external script that does this, you should subclass `Worker` and override `perform_job`. The `rqworker` script allows you to specify your own `Worker` class.
