### ISSUE TITLE
Broken pipe with multiprocessing if not worker restart

### ISSUE THREAD

**Issue by olingerc** [nvie/rq#626]
Hi,

Ever since I started using the multiprocessing library in one of my jobs I have to explicitly restart all workers whenever I change something in my code. The error I get is:
```Error: <type 'exceptions.IOError'>, [Errno 32] Broken pipe```
and I only get it when running that specific job.

It is not  major problem but before using multiprocessing I did not have to do that. Am I doing something wrong?

**Comment by selwin** [comment]
You probably need to terminate all processes before your function returns.

**Comment by olingerc** [comment]
I came back to this since I have a task were multirpocessing is essential.
I found out that this line alone already causes the error. So I did not even start any processes. As said in the title, restarting all workers after changing any code resolves the problem, but it is tiresome.
```
pool = mp.Pool(processes=THREADS, maxtasksperchild=1)
```
