### ISSUE TITLE
job.delete() should also remove it from StartedJobRegistry

### ISSUE THREAD

**Issue by olingerc** [nvie/rq#632]
Currently jobs stay in the StartedJobRegistry even when job.delete is called. I know that the registries are cleaned up every hour, but maybe this could be added to the delete function in the job class (or cancel?).
I give the user the option to delete jobs even while they are running.

On the other hand, the StartedJobRegistry is currently not used anywhere else, so letting the automatic cleanup do its job might be sufficient? What do you think?

``` python
registry = StartedJobRegistry(job.origin, self.connection)
registry.remove(job, pipeline=pipeline)
```

**Comment by selwin** [comment]
Yeah, deleting the job should also remove it from the registry. PR welcome :)

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/810
