### ISSUE TITLE
Encoding error on Ubuntu 14.04.3 LTS x64 with Python 3.4.3

### ISSUE THREAD

**Issue by dpnishant** [nvie/rq#634]
rqworker works perfectly fine with Python 3.5 on OS X 10.11.1 but I'm getting the following error when ever I want to run rqworker on a Ubuntu 14.04.3 LTS x64 with Python 3.4.3. The same error persists on Ubuntu 12.x also.
-----------------------------SNIP-----------------------------
root@ubuntu:~# rqworker
Traceback (most recent call last):
  File "/usr/local/bin/rqworker", line 11, in <module>
    sys.exit(worker())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.4/dist-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: 'str' does not support the buffer interface
root@ubuntu:~# python3 -V
Python 3.4.3
root@ubuntu:~# 
----------------------------/SNIP-----------------------------

Please help me fix this.

**Comment by dpnishant** [comment]
Edit.

The same error persists even if I upgrade my python version to 3.5.1 on a Ubuntu 14.x LTS server. Is there anything I'm missing out?

**Comment by dpnishant** [comment]
I'm sorry this was not really an issue with rq. It was a locale issue on my system and I resolved this by running the following commands:
`export LC_ALL=C.UTF-8`
`export LANG=C.UTF-8`

**Comment by patkaehuaea** [comment]
And...you saved me a ton of time :+1:

**Comment by agusfantasy** [comment]
8 hours to figure out also googling this thing.Thanks a lot @dpnishant

**Comment by michaelangelorayco** [comment]
Thanks @dpnishant I just slightly modified it with
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
