### ISSUE TITLE
is -w argument per queue or global ?

### ISSUE THREAD

**Issue by jeremy-rutman** [nvie/rq#643]
is the -w argument per queue or global ?

e.g. can I do 

'''
rqworker  -w mypackage.myworkerclass.MyWorker  myqueue1 -w rq.Worker myqueue2 
'''

**Comment by proofit404** [comment]
`--worker-class` is usual click option so it applied globally to worker command. You can't specify different worker class for each queue within command line interface.

**Comment by nvie** [comment]
Correct, you can specify a custom class instance for running the default `rqworker` script's command line flags. If you want fancier behaviour, you can write your own worker script. `rqworker` just ships for convenience, you don't have to use it.
