### ISSUE TITLE
Jobs with return values where bool(rv) is not True or False succeed but log an exception. 

### ISSUE THREAD

**Issue by liorsbg** [nvie/rq#644]
I came across this bug(?) because my function was returning a numpy array.
The job succeeded but the log showed: 
`...
File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 535, in main_work_horse
    success = self.perform_job(job)
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 608, in perform_job
    if rv:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

The offending line: https://github.com/nvie/rq/blob/master/rq/worker.py#L608

This is because numpy arrays cannot be "iffed" (they do not have a single bool value). It's a bit of a weird implementation choice on their part. It might be the case however, that other functions that users write or use have weird `__nonzero__()` or `__bool__()` implementations. This is minor, but I'm pretty sure it could be fixed without any side-effects by modifying the line to `if rv is not None: ` 

wdyt?

**Comment by selwin** [comment]
The approach you suggested is good. Please open a pull request :)

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/690
