### ISSUE TITLE
subprocess calls, invoked by a job, do not terminate/stop upon timeout error

### ISSUE THREAD

**Issue by rkubik** [nvie/rq#646]
In one of my rq jobs I have a timeout set at a minute:

```
# job deco for getting queue and setting timeout
@job('default', timeout=60)
def collect_data(id):
    job = get_current_job(get_connection())
    job.meta['id'] = id
    job.save()
    process = subprocess.Popen('...', shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = process.communicate()
    job.meta['output'] = stdout + stderr
    job.save()
    return process.returncode
```

If the shell command takes longer than a minute the job fails and throws a timeout error:

```
Job exceeded maximum timeout value (60 seconds) 
```

But the subprocess call is still running in the background. 

**Current Solution:**

Save the process PID in the jobs meta object and have the error handler check if the PID is running and terminate if so.

**Another Solution:**

Use threading to monitor subprocess calls with its own timeout. The issue with this method is that the other non-subprocess job work will not have a timeout.

Is there a better way?

**Comment by proofit404** [comment]
Hello.

You can rewrite you subprocess job in proper way:
```python
with Popen(['...'], shell=True, stdout=PIPE, stderr=PIPE) as process:
    try:
        stdout, stderr = process.communicate()
    except JobTimeoutException:
        logger.error('Process was killed by timeout.')
        raise
    finally:
        if process.poll() is None:
            process.kill()
            stdout, stderr = process.communicate()
```
So you doesn't need watchdog thread or additional clean up tasks. Note that `process.poll()` may return `None` for already killed processes so check for error number additionally.

**Comment by selwin** [comment]
As @proofit404 explained, this is not really an RQ issue :). Closing.

**Comment by rkubik** [comment]
Unfortunately no context support for subprocess in 2.7, but I understand the concept. Much thanks @proofit404

**Comment by proofit404** [comment]
You're welcome. Same behavior can be implemented with one more `try/finally` block without context manager.
