### ISSUE TITLE
Sample Worker Management Script / Strategy

### ISSUE THREAD

**Issue by jbremson** [nvie/rq#649]
I need to make sure there is a live worker running for every core on my server 24/7.

Is there a sample script or strategy for making sure the right number of workers are up and alive?

**Comment by proofit404** [comment]
You can use tools like `systemd`, `supervisor` or `foreman` to be sure that proper number of workers are running in the production.

**Comment by jbremson** [comment]
But how do I know if the workers are actually alive?

The count between rqinfo for workers and against rqworker processes with ps is rarely the same. Many of the workers are zombies.

**Comment by selwin** [comment]
How do you run your workers currently? I find it strange that many of your workers become zombies. Even zombies shouldn't show on rqinfo after the worker keys expire.

**Comment by jbremson** [comment]
Supervisor.

I think the issue was that very long mysql queries were failing on TTL. The
worker would be dropped, but the process would still be running, not dead,
but not ever completing either. So the process would linger around and not
be restarted by supervisor.

When this happened often enough I would lose all my workers from rq's
perspective, but they'd still be alive according to supervisor.
