### ISSUE TITLE
async=False, status should be 'passed'

### ISSUE THREAD

**Issue by illume** [nvie/rq#655]
Seems status is not correct with async=False. It should be set to 'finished' when done, but is not.

>>> q = Queue('low', async=False)
>>> job = q.enqueue(fib, 8)
>>> job.result
21
>>> job.status
'finished'

**Comment by selwin** [comment]
Mind making a PR for thia?

**Comment by th3hamm0r** [comment]
This seems to be fixed with the PR https://github.com/nvie/rq/pull/640

**Comment by selwin** [comment]
Fixed
