### ISSUE TITLE
Worker prematurely ending job

### ISSUE THREAD

**Issue by jjwon0** [nvie/rq#663]
Hi,

I'm using RQ worker to run a function which has a retry mechanism built using `tornado.ioloop.IOLoop`.  However, inducing any sort of delay on the callback is resulting in the worker completing the job prematurely, so the retry mechanism doesn't run.

Here's the problematic snippet:
```
self.io_loop.add_callback(
    callback=lambda: self.io_loop.call_later(
        delay=self._get_retry_delay(attempt_number),
        callback=partial(retry, attempt_number)
    )
)
```

If `delay=0`, `retry(attempt_number)` is successfully called.  However, since `call_later` is nonblocking, the job is being completed.  Is there a way around this?

**Comment by proofit404** [comment]
First of all provide full source code example.  As far as I can tell you create new tornado event loop within each task? If so prepare event loop by adding interesting callback to it, start event loop, check for result and rerun it until necessary callbacks will be triggered.  If you're using asyncio eventloop there is an `run_until_complete(future)` function. It can prevent you from rerunning event loop each time.

**Comment by jjwon0** [comment]
Sorry, here's the full source code with a few redactions.

We grab a new instance of `tornado.ioloop.IOLoop` when the singleton is instantiated, not on every try.  I tried changing the calling pattern as to not use singletons, but that change anything.

```
from functools import partial
import threading

from tornado.ioloop import IOLoop
from our_utilities import Lazy  # a descriptor for lazy-loaded values

class RetryManager:

    instance = Lazy(lambda: RetryManager())

    def __init__(self):
        self.retry_counter_factory = RetryCounterFactory.instance

        self.io_loop = IOLoop.instance()
        self.retry_thread = threading.Thread(
            target=lambda: self._start_io_loop()
        )
        self.retry_thread.start()

    def _start_io_loop(self):
        self.io_loop.make_current()
        self.io_loop.start()
        self.io_loop.close()

    def schedule_retry_for_user(self, receiver_id, payload):

        retries_left = self.retry_counter_factory.get_counter(
            obj_id=receiver_id,
            payload=payload
        )

        def retry(attempt_number):
            # This function is not being called due to the job being completed.

            try:
                # Make POST request, etc...
            except Exception:
                self.schedule_retry_for_user(receiver_id, payload)

        if retries_left <= 0:
            raise MaximumRetriesExceededError()
        else:
            attempt_number = self._get_attempt_number(retries_left)

            self.io_loop.add_callback(
                callback=lambda: self.io_loop.call_later(
                    delay=2,
                    callback=partial(retry, attempt_number)
                )
            )

            retries_left.decr()

    def stop(self):
        if self.io_loop:
            self.io_loop.stop()
        if self.retry_thread:
            self.retry_thread.join()
```

**Comment by proofit404** [comment]
Maybe I don't understand your case but why you trying to solve this with tornado? Is there any tornado related code you need to use with rq? I think it will be simple to use `requests` together with `FailedQueue.requeue`.

Can you describe actual problem you're trying to solve?

**Comment by jjwon0** [comment]
I actually rewrote it yesterday to use RQ instead of using an IOLoop, and
it works as expected. So that's good.

The original code was written with Tornado because we want to use callbacks
to schedule retries on the order of seconds with an exponential
backoff after initial failure.  RQ Scheduler, by default, polls Redis every
60 seconds which might not be enough, and we're worried about performance
issues from polling Redis too frequently.

So I guess, are there performance implications from polling Redis every
say, 5 seconds instead (we use Redis for other things also)? If not, then
we can just use that. I noticed that Celery polls every 0.5s, actually.

On Wednesday, February 24, 2016, Malyshev Artem <notifications@github.com>
wrote:

> Maybe I don't understand your case but why you trying to solve this with
> tornado? Is there any tornado related code you need to use with rq? I think
> it will be simple to use requests together with FailedQueue.requeue.
>
> Can you describe actual problem you're trying to solve?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvie/rq/issues/663#issuecomment-188222269>.
>


-- 
Jason Won
@jjwon0
http://jjwon.com

**Comment by proofit404** [comment]
We use celery ETA param for delayed calls of this kind. But since rq doesn't support it I can't give you best practice on this topic.

**Comment by jjwon0** [comment]
Okay, thanks anyways.  I'll close this with the learning that RQ will terminate jobs that may have callbacks or delays assigned to them, because it has no way of differentiating whether the process has finished or whether it is waiting for a callback.
