### ISSUE TITLE
depends_on and result_ttl

### ISSUE THREAD

**Issue by horida** [nvie/rq#675]
When enqueueing a job depending on a former one created with `result_ttl=0`, it will not be executed since no reference to the first jobs was found. All this silently without any warning.
For example:

    queue = Queue(name='my_q)
    first_job = queue.enqueue(my_func1, result_ttl=0)
    second_job = queue.enqueue(my_func2, depends_on=first_job)  # my_func2 won't be executed

If this is correct, it might be worse mentioning in the documentation (http://python-rq.org/docs/ "Enqueueing jobs").
I for myself would prefer an Exception when creating the queues saying that a job with `result_ttl=0` can't be referenced in `depends_on`.

**Comment by selwin** [comment]
I also prefer raising an exception when creating a job that has an unknown dependency. Do you mind opening a PR for this? :)

**Comment by horida** [comment]
@selwin I'm not sure about the Exception

**Comment by proofit404** [comment]
Maybe `ValueError` will be more suitable for this case?

**Comment by selwin** [comment]
Actually, now that I think about it, the second job should still execute as long as it's still enqueued when the first job is in RQ. When the first jib has finished executing, the worker should enqueue all jobs dependent on the first one, regardless of the first job's result_trl.

Maybe this is a bug, I'll have to look into it.

**Comment by selwin** [comment]
I haven't been able to spot any bug in the current job dependency implementation. Enqueueing a job that depends on another job with result_ttl==0 should work.

I'm closing this issue for now. Please reopen if you can provide a failing test case that demonstrates the opposite.

**Comment by horida** [comment]
@selwin Here you have an example that shows the issue. With `result_ttl=0` you won't get the logging message from `func2`

run with `rqworker -u redis://guest:@localhost:6379 test_queue`

runner.py:
```
import test_rq_module      
                           
if __name__ == '__main__': 
    test_rq_module.run_rq()
```

test_rq_module.py:
```
import time                                                           
import logging                                                        
                                                                      
from redis import Redis                                               
from rq import Connection, Queue                         
                                                                      
                                                                      
def func1():                                                          
    logging.warning('start func1')                                    
    time.sleep(1)                                                     
    logging.warning('finish func1')                                   
                                                                      
                                                                      
def func2():                                                          
    logging.warning('start func2')                                    
    time.sleep(1)                                                     
    logging.warning('finish func2')                                   
                                                                      
def run_rq():                                                         
    with Connection(Redis.from_url('redis://guest:@localhost:6379')): 
        queue = Queue(name='test_queue')                              
        job1 = queue.enqueue(func1, result_ttl=0)  # doesn't work     
        #job1 = queue.enqueue(func1)  # works                         
        queue.enqueue(func2, depends_on=job1)          
```

**Comment by horida** [comment]
@selwin I don't have the permissions to re-open this issue. Do you prefer that I open an new issue or can you re-open it (in case that you confirm that my example shows the same behavior for you)

**Comment by selwin** [comment]
Yes, it shows the same behavior when I tried it. I'll try to take a look at this tonight.

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/commit/e9d227c3df321ce2bd27d174b9f905f413dc4ef5 .
