### ISSUE TITLE
Unique jobs?

### ISSUE THREAD

**Issue by tume** [nvie/rq#678]
Didn't find any mention that is it possible to have unique jobs (enqueue/run only once). My current need is to make sure that only one job with specific args is in queue. I was thinking that I could do this with job_ids but seems that you can enqueue as many jobs you like with same the same id.

Is there a builtin support or any known way to achieve this?

**Comment by proofit404** [comment]
Try to use some kind of lock build on top of redis with ttl set. Try to acquire it before enqueue your jobs.

**Comment by jlopex** [comment]
If you have a way to know beforehand the job id, maybe you can check if any job with that id is already present on the queue.

**Comment by selwin** [comment]
This is not a feature that RQ aims to solve. You should build your own uniqueness checking logic before putting it in RQ.

**Comment by yunderboy** [comment]
@tume a solution would be to create a DB entry and get the generated ID from that specific entry and use that.

**Comment by samuelcolvin** [comment]
At TutorCruncher we have an extension to rq with we call `tracked_jobs`, it's effectively an alternative decorator which is used thus:

```py
@tracked_job('generate_invoices_{company}')
def generate_invoices(start_date: date, end_date: date, *, company: int):
    ...
```

If it's called with `generate_invoices.delay(x, y, 123) ` the job id would be `'generate_invoices_123'`. Only one job can be ongoing with that job id. It also provides other useful methods `generate_invoices.ongoing(*, company) -> bool` and `generate_invoices.status(*, company)`.

Under the hood `tracked_job` atomically gets and sets the job id as a value in redis before enquiring the job and deletes it after the job finishes.

Obviously if there are no kwarg variables in the job id template the job will be globally unique.

Personally I disagree with @selwin, I think this is generically useful enough and close enough to rq to be a good candidate to add the rq.

Thoughts?

**Comment by inactivist** [comment]
> Try to use some kind of lock build on top of redis with ttl set. Try to acquire it before enqueue your jobs.

Here's one such Redis lock context implementation:

https://chris-lamb.co.uk/posts/distributing-locking-python-and-redis
