### ISSUE TITLE
Is it possible to integrate RQ with Ruby

### ISSUE THREAD

**Issue by iaptsiauri** [nvie/rq#679]
I know that RQ is only python. But my question is following whether it is possible or not to register jobs with resque or sidekiq and afterwards use the RQ worker to perform the job

**Comment by proofit404** [comment]
You can write some RPC service in python which will submit a job into `rq` and return an id you can use to check the result later.

**Comment by jlopex** [comment]
Where would you implement the Logic of each job? Python or Ruby code?

**Comment by nvie** [comment]
RQ is Python only and that can't just change. If you want interoperability, you're better off using RPC (as @proofit404 suggests) based tools or build something using ZeroMQ.
