### ISSUE TITLE
Multiple workers per queue?

### ISSUE THREAD

**Issue by sivabudh** [nvie/rq#688]
Is it possible to have more than 1 worker per queue?

For example, In Huey, one can set the number of workers.

See:
https://huey.readthedocs.org/en/latest/

**Comment by proofit404** [comment]
Start more worker processes.

**Comment by jlopex** [comment]
Of course you can, as @proofit404 said just launch more worker processes.

A way to do it is using supervisor on top of your worker, a sample is available on RQ documentation [http://python-rq.org/patterns/supervisor/](url)
