### ISSUE TITLE
Ability to dump failed job exceptions in rq info

### ISSUE THREAD

**Issue by crazyhatfish** [nvie/rq#692]
Currently I don't think there is any way to view the exceptions the failed jobs raised from the `rq` interface, I propose a simple dump command which would iterate over the failed queue and output `exc_info` to `stdout`.

The equivilant of the following snippet:

    job_queue = Queue("failed", connection=Redis())
    for job in job_queue.get_jobs():
        click.echo(job.getid())
        click.echo(job.exc_info)

**Comment by selwin** [comment]
You should use an RQ monitoring tool like Django-RQ for this. Alternatively, you could also write your own script like what you proposed :)

**Comment by crazyhatfish** [comment]
I did write my own script - that is it. :) I thought it would add to the convenience, being so lightweight it seems wrong to require a dependency (especially one that then depends on Django) for such a elemental part of debugging.
