### ISSUE TITLE
SimpleWorker.work results in TypeError

### ISSUE THREAD

**Issue by rebeckag** [nvie/rq#696]
Running the latest code (cd04143) with the following minimised example

```
from rq import Queue, SimpleWorker
from redis import StrictRedis

q = Queue(connection=StrictRedis())
worker = SimpleWorker([q], connection=q.connection)
worker.work(burst=True)
```

results in a `TypeError`:

```
Traceback (most recent call last):
  File "test_rq.py", line 87, in <module>
    worker.work(burst=True)
  File "rq/rq/worker.py", line 419, in work
    setup_loghandlers(logging_level)
  File "rq/rq/logutils.py", line 19, in setup_loghandlers
    level_int = getattr(logging, level)
TypeError: getattr(): attribute name must be string
```

I'm not sure what the right course of action is to fix this, based on the fact it's apparently a fix for Python 2.6 according to 0a49e24.

**Comment by jlopex** [comment]
This seems related with my PR from a few weeks ago.

I think logging.INFO is an integer and this is expecting a string.

A quick solution until a new PR is pushed could be using a logging_level on your code.

```
worker.work(burst=True, logging_level="INFO")
```

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/697
