### ISSUE TITLE
enqueue_call timeout param not working

### ISSUE THREAD

**Issue by WillNye** [nvie/rq#698]
I am trying to change the timeout on an rq job but nothing seems to work. I've got something to the effect of:

```
my_queue = Queue('my_task', connection=Redis())

job_args = (1, 2, 4)

my_queue.enqueue_call(
                    my_func,
                    args=job_args,
                    timeout=2700
            )

```
but I'm still getting

`JobTimeoutException: Job exceeded maximum timeout value (180 seconds)
`
I've got so desperate I even tried going into the rq module queue.py and changing the default argument for timeout to 2700 and DEFAULT_TIMEOUT (variable defined in the Queue class, which contains the enqueue_call method). Am I missing something or is there an issue with this anyone knows about? Thanks!

**Comment by jlopex** [comment]
Why are you using the enqueue_call method? I'm using the Queue.enqueue method with custom timeout values and I have not observed any issues.

**Comment by WillNye** [comment]
As per the python rq docs: "Before RQ 0.3.0, the `.enqueue()` method accepted a `timeout` keyword argument, but this introduced an ambiguity as it was impossible to pass that keyword argument to the target function. So, from RQ >= 0.3.0, you can use `.enqueue_call()` for that."

**Comment by jlopex** [comment]
Ok, I always used the enqueue method, it seems that both methods support the timeout value.

https://github.com/nvie/rq/blob/master/rq/queue.py#L246

I have no idea why this is not working on your setup, I just rechecked using master branch and it seems to work on my end.

**Comment by selwin** [comment]
As @jlopex mentioned, please use the `enqueue` method. I'll update the docs later.
