### ISSUE TITLE
Using RQ on PRS/Torque/SunGrid clusters

### ISSUE THREAD

**Issue by BoPeng** [nvie/rq#705]
I am a bioinformaticist working in traditional PRS/Torque/SunGrid clusters. I have grown unsatisfied with working with job queues of such systems because of long delays and difficulties in monitoring job status. I have read about RQ and think it can be a variable alternative to PRS, if I can
1. Start RQ on the head node that create jobs.
2. Submit workers through PRS to computing nodes.
3. RQ will communicate the workers to dispatch jobs to them.

This will essentially speaking create a mini-cluster inside a cluster system and by-pass PRS for large numbers of small jobs, and it should in theory work as long as the head node can communicate with computing nodes (workers through redis). I am however surprised to see no discussion on such usages so I am wondering if and how users of RQ use RQ on such cluster systems, and if I have missed something obvious that prevents the application of RQ on them.

**Comment by selwin** [comment]
I'm not sure what you're requesting, but if you just want to run RQ on a Redis cluster for performance/reliability reasons. This PR allows you to run RQ on Redis Sentinel: https://github.com/nvie/rq/pull/808

I'm closing this issue for now, but please reopen if I misunderstood your request.
