### ISSUE TITLE
Workers customization

### ISSUE THREAD

**Issue by eroncastro** [nvie/rq#712]
Hi, guys! Is it possible to customize workers so that, for example, I have 3 workers that already have loaded selenium with PhantomJS so I can crawl a website?

Thanks in advance!

Eron

**Comment by proofit404** [comment]
Hello.

Suppose you have phantom.js python wrapper called `Phantom`.

Lets create variable to hold its instancies.

```python
from rq.local import LocalStack

_phantom_stack = LocalStack()
```

We need a function which gives as access to this stack

```python
def get_phantomjs():
    phantom = _phantom_stack.top
    if not phantom:
        raise Exception('Run outside of worker context')
    return phantom
```

Now we need to put persistent `Phantom` instance to this stack on `rq`
worker start

```python
from rq.worker import Worker

class MyWorker(Worker):

    def work(self, burst=False, logging_level='INFO'):
        _phantom_stack.push(Phantom())
        return super(MyWorker, self).work(burst, logging_level)
```

Now use it in your job

```python
def my_job():
    phantom = get_phantomjs():
    phantom.do_stuff()
```

Also you can overwrite `Worker.execute_job` and check if you `Phantom` instance go well after job execution.

Hope this helps.

Regards, Artem.

**Comment by selwin** [comment]
This is not a realy issue, closing :)
