### ISSUE TITLE
Incorrect number of workers in rqinfo

### ISSUE THREAD

**Issue by davidhariri** [nvie/rq#713]
If I kill all the worker processes with:

```bash
pkill -f rqworker &
```
And then reinstantiate them with:

```bash
rqworker high normal low &
rqworker high normal low &
rqworker high normal low &
rqworker high normal low &
rqworker high normal low &
rqworker high normal low &
rqworker high normal low &
rqworker high normal low &
```

rqinfo will show that I have 16 workers instead of 8. Doing this:
```bash
ps aux | grep rqworker
```
yields 8 pid's as expected.

After some time rqinfo will update itself. Restarting rqinfo doesn't help. Am I doing something wrong or is this a known issue?

**Comment by proofit404** [comment]
`rq info` shows worker information based on information stored in redis. When worker disappears it set death date to it info hash. This information hash persist in redis for sometime. `rq info` show correct number of workers right after information keys for killed workers expires.

**Comment by davidhariri** [comment]
@proofit404 Is there a way to kill a worker process that properly clears itself from Redis?

**Comment by proofit404** [comment]
Behaviour described above is desired behaviour by design.

You can overwrite `Worker.register_death` method to remove this key instead. Or filter workers with death date in `rq info` yourself.
