### ISSUE TITLE
Failed queue with a lot of "started" jobs

### ISSUE THREAD

**Issue by jibaku** [nvie/rq#716]
On a project, I've a lot of jobs that finish in the failed queue with the status "started". What can cause this type of problem and how can I solve it ?

**Comment by proofit404** [comment]
It looks like an exception happens during job execution, but worker can't set job status to failed. [Here](https://github.com/nvie/rq/blob/bc4fc5595ff6fa9f34ea2a0f7c8fd040af855591/rq/worker.py#L617-L622) redis pipeline which set job status can silently fail. And [then](https://github.com/nvie/rq/blob/bc4fc5595ff6fa9f34ea2a0f7c8fd040af855591/rq/queue.py#L432-L441) `rq` create a new pipeline which push failed job to the failed queue. Try to find worker log messages and analyze the reasons for those exceptions.

**Comment by selwin** [comment]
Not a real solution, but we should use logging to display appropriate error messages when this happens so it can be easily debugged.
