### ISSUE TITLE
Support specifying timeout values using strings instead of ints

### ISSUE THREAD

**Issue by nvie** [nvie/rq#72]
It would be nice to be able to specify timeouts using strings instead of ints (seconds).

Currently, you need to do this:

```
high = Queue('high', default_timeout=8)  # 8 secs
low = Queue('low', default_timeout=600)  # 10 mins
low.enqueue(really_really_slow, timeout=3600)  # 1 hr
```

It would be a nice little touch to also support the following timeout specs:

```
high = Queue('high', default_timeout='8s')
low = Queue('low', default_timeout='10m')
low.enqueue(really_really_slow, timeout='1h')
```

Only `'s'`, `'m'` and `'h'` suffixes have to be supported IMHO.

**Comment by luojiebin** [comment]
#818

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/818
