### ISSUE TITLE
Sharing a DB connection pool among Workers

### ISSUE THREAD

**Issue by mgood1** [nvie/rq#720]
We're currently using several worker pools to handle various jobs that interact with a PostgreSQL DB, and I'm running into issues with inefficient DB connection management. I'd like to be able to have a single pool for the worker processes to draw from, or barring that, for each worker to have its own connection for use in any jobs it may handle. However, I'm running into problems working out the best way to implement this. My current intention is to aim towards having the workers create a connection when they spawn, but thought I'd see if there are any better options out there.

Thanks!

**Comment by proofit404** [comment]
If I understand correctly you create DB connection each time job executes and try to get rid of it. Create connection pull ones at worker start for example. You have an option to override `work` method and create connection pool preventively. Try something like this:

```python
from rq.local import LocalStack
from rq.worker import Worker

_pools = LocalStack()


class MyWorker(Worker):

    def work(self, *args, **kwargs):
        _pools.push(NewConnectionPool())
        return super(Worker, self).work(*args, **kwargs)


def get_pool():
    return _pools.top
```

Then use it in your job

```python
def my_job():
    with get_pool() as conn:
        do_stuff(conn)
```

**Comment by mgood1** [comment]
@proofit404 - Thanks! I'll be attacking the issue this week, and will try this!

**Comment by proofit404** [comment]
Feel free to DM me if you need more detailed information or meet a problem.

**Comment by grafixoner** [comment]
@proofit404 I haven't had any luck trying to get a shared Mongodb connection in RQ is that something you could maybe help me with?  I'm processing only about 10k jobs an hour and my worker is only doing 5-10 req per second right now which backs up the queue so desperately trying to get everything loaded in the worker process.  I tried subclassing which works but in my classes I can't access the worker process.

**Comment by proofit404** [comment]
Sure. What solution did you try?

**Comment by grafixoner** [comment]
Well I set up my Custom worker and set up the DB connections which work.  I can access them inside the Redis connection loop in the code below. However when my jobs run, I can't access these variables.  I tried setting self vars with no luck because my jobs don't seem to have any awareness of these worker processes nor its variables.  I also had tried to set up a connection pool like yours above but the same problem, inside my running processes they don't have access to anything the worker process does.  

`class CustomWorker(Worker):
    def __init__(self, *args, **kwargs):
        import pdb; pdb.set_trace()  # breakpoint 4efcba64 //

        Worker.__init__(self, *args, **kwargs)
        db_pool = db.mongodb()
        authdb_pool = db.mongooauthdb()

        logging = client.logging.ListMaster(db_pool, authdb_pool, db_pool, env)

if __name__ == '__main__':
    with Connection(redis):
        worker = CustomWorker(map(Queue, listen))
        worker.work()`

**Comment by proofit404** [comment]
Breakpoint won't work in the subprocess unless you're using an advanced debugging tool like [Manhole](https://github.com/ionelmc/python-manhole).

You're trying to save db_pool in the worker instance, but `self` within a job will be a job instance. Try to build global connection manager like I do in the example above.

**Comment by grafixoner** [comment]
So when I try to define as you have above I get an exception that super has no attribute of work.

'''Traceback (most recent call last):
  File "worker.py", line 35, in <module>
    worker.work()
  File "worker.py", line 26, in work
    return super(Worker, self).work(*args, **kwargs)
AttributeError: 'super' object has no attribute 'work''''

**Comment by proofit404** [comment]
It is **very strange** but you can try `Worker.work(self, *args, **kwargs)`

**Comment by grafixoner** [comment]
Well that fixes the error however still no connection pool. ``` get_pool()``` returns None in the jobs that are firing.  again in the ```with Connection(Redis)``` loop I have access to the pool but not in the executing jobs themselves.   

Do you have a full simple example of a shared DB connection in an executed job?

**Comment by grafixoner** [comment]
Even just setting up a simple example like is shown in the "Performance Notes" to import libraries before the fork doesn't work.  I can't even access those imports.  

```#!/usr/bin/env python
import sys
from rq import Connection, Worker

# Preload libraries
import library_that_you_want_preloaded

# Provide queue names to listen to as arguments to this script,
# similar to rq worker
with Connection():
    qs = sys.argv[1:] or ['default']

    w = Worker(qs)
    w.work()```

**Comment by proofit404** [comment]
Does you open your sockets on the shared mode? I forgot exact flag name. But the meaning it can be used from different process and survive fork.

**Comment by proofit404** [comment]
But of course it won't fix the `None` problem. Try to use bare list as global variable instead if LocalStack.

**Comment by grafixoner** [comment]
So I'm actually a complete idiot, all I had to do was ```import myJobs``` which includes the db connections before my ```Worker.work()```.  My queue runtime went from over an hour down to about 8 minutes without any custom worker and DB connections are under control again.

**Comment by grafixoner** [comment]
OH and thanks for all your help! Much appreciated.

**Comment by proofit404** [comment]
Great news, I'm glad you solve it!

**Comment by atkinsj** [comment]
@grafixoner are you able to share the code you got working for this? I'm still struggling here!

**Comment by grafixoner** [comment]
```
import os
import sys
import redis as Redis
from rq import Worker, Queue, Connection
import logging

listen = ['default', 'listener', 'data', 'delivery', 'digest', 'broadcast']

from redis import Redis
if sys.argv[2] == 'dev' or sys.argv[2] == 'local':
    redis = Redis()
else:
    redis = Redis('xxx.xxx.xxx.xxx', 6379)

"""
This is the execution code which contains the Mongo DB_POOL so we don't create multiple connections every time a job is fired. 

import user.subscriptions
"""

import user.subscriptions

if __name__ == '__main__':
    with Connection(redis):
        worker = Worker(map(Queue, listen))
        worker.work()
```

@atkinsj There really isn't much to share.  Basically my database connection pools are set up in user/subscriptions.py which includes the code that fires once RQ schedules them.  Then I have a simple worker that fires off jobs, you will need to import your classes that are creating the DB_POOL connection prior to starting the worker loop.   

Here is my worker.py.  All my job execution code is inside of user/subscriptions.py but that doesn't have really anything to make the DB_POOL work, just make sure that DB_POOL is loaded in your classes inside if your worker.py.

**Comment by oinquer** [comment]
I know this is basically Necro-ing a "non-issue" but i cant seem to get this working:
I am sure i am getting something fundamentally wrong...
missing an import somewhere, but with the example above i couldnt work it.
a very simple example of what i tried:

worker.py:

```
from rq.local import LocalStack
from rq.worker import Worker
from rq import Connection
_pools = LocalStack()

class MyWorker(Worker):

    def work(self, *args, **kwargs):
        _pools.push("Test")
        return super().work(*args, **kwargs)

def get_pool():
    return _pools.top

if __name__ == "__main__":
    with Connection():
        w = MyWorker(['default'])
        w.work()
```


job.py:

```
from worker import get_pool

def my_job():
    print(get_pool())
```


run.py:
```
from redis import Redis
from rq import Queue
from job import my_job

if __name__ == "__main__":
    queue = Queue(connection=Redis(host="127.0.0.1", port=6379))
    queue.enqueue(my_job)
```

what am i doing wrong? Thank you.

**Comment by masgari** [comment]
Hi @oinquer 

Use SimpleWorker, in your case: 

Change:
> py class MyWorker(**Worker**):

to:
```py
class MyWorker(SimpleWorker):
```

I had a similar problem (with `rq` version 1.5.1), after adding/printing `os.getpid()` to my jobs, noticed each job is running in different process (or `sub process`). 

Default `Worker`, creates a sub process:
```py
    def execute_job(self, job, queue):
        """Spawns a work horse to perform the actual work and passes it a job.
        The worker will wait for the work horse and make sure it executes
        within the given timeout bounds, or will end the work horse with
        SIGALRM.
        """
        self.set_state(WorkerStatus.BUSY)
        self.fork_work_horse(job, queue)
        self.monitor_work_horse(job, queue)
        self.set_state(WorkerStatus.IDLE)

```
