### ISSUE TITLE
change datetime formatting to include milliseconds

### ISSUE THREAD

**Issue by samuelcolvin** [nvie/rq#721]
I propose `'%Y-%m-%dT%H:%M:%SZ'` in `utcformat` becomes `'%Y-%m-%dT%H:%M:%S.%fZ'`, note the `%f` to give more exact times.

This is because we have numerous jobs with take around a second and are queued for around a second and without `started_at` and `ended_at` being saved with ms it's impossible to get a good idea of how long their really taking.

I can see from the comments in `utcparse` that something similar was previously the case so I wanted to canvas opinions on whether this was a possibility before submitting a PR?

**Comment by samuelcolvin** [comment]
see [code here](https://github.com/nvie/rq/blob/master/rq/utils.py#L158-L167)

**Comment by selwin** [comment]
Yeah, I think this is a good idea. PR welcome :)

**Comment by theodesp** [comment]
@samuelcolvin are you willing to make a PR for this?

**Comment by samuelcolvin** [comment]
Hi @theodesp, thanks for the prompt, I'd forgotten about this.

I'm submit a PR once #874 is merged.

**Comment by selwin** [comment]
@samuelcolvin #874 has been merged 😊. I personally want to see this supported in RQ because this may be useful in collecting worker/job metrics - something I’ll be working on soon.
