### ISSUE TITLE
Can't get jobs from a queue

### ISSUE THREAD

**Issue by DavidVentura** [nvie/rq#723]
I want to get a list of all the jobs on a given queue. How can I do this? I could call my own function to enqueue jobs and store every job_key but that defeats the point

I start my worker like this:
```python
 conn = redis.from_url(redis_url)
 q = Queue('default', connection=conn)
  
  if __name__ == '__main__':
      with Connection(conn):
         worker = Worker([q])
         worker.work()
```

Then add jobs either with decorators (eg: `  @job('default',connection=conn, timeout=3600*2, result_ttl=3600*2)`) or with an explicit call using the same queue ( `job = q.enqueue(tasks.long_job, args=("test",), ttl=403)`)

But I can't get a list of all jobs. Even running rq info gets me:
```bash
# (running) 
$ rq info 
high         | 0
failed       | 0
default      | 0
3 queues, 0 jobs total

pc-david.30094 busy: default
1 workers, 3 queues
# (finished)
$ rq info 
high         | 0
failed       | 0
default      | 0
3 queues, 0 jobs total

pc-david.30094 idle: default

```
This works 

```python
 def result(job_key):
     """Get job result from key. throws exception if non-existing key"""
     job = Job.fetch(job_key, connection=conn)
     if job.is_finished:
         return ("Result: %s" % str(job.result), 200)
     else:
         return ("Process: %s" % json.dumps(job.meta), 202)
```

but `q.jobs()` is always empty

**Comment by scottwernervt** [comment]
`q.jobs` is a property on the `Queue` class, not a function. Does the following work?

```python
jobs = []
queue = Queue('default', connection=conn)

for queue_name in queue.all():
    jobs.extend(queue_name.jobs)

return jobs
```

**Comment by DavidVentura** [comment]
This worked, but only until I restarted the server. Now I always get 0.

```
<Queue 'failed'>
0
<Queue 'default'>
0
<Queue 'high'>
0
```

Even after explicitly putting a dumb, long job on the queue. But still, fetching with ` job = Job.fetch(job_key, connection=conn)` gets me the job. Ideas?

**Comment by proofit404** [comment]
Job is live until its result_ttl not reaches the end of life. But job can not present in any queue or registry. It totally normal. If you need more deep explanation if this idea I can write it tomorrow. It's late night in Russia.

**Comment by DavidVentura** [comment]
Then how do I track progress if I can't iterate over the running job? I've stored a few values on the meta key of the job but the only way I have to recover the job instance is by calling getJob(job_key). And this job_key is not stored in the queue, so I have to store it myself on a list.

**Comment by selwin** [comment]
Running jobs are stored in `StartedJobRegistry`. It's a sorted set which stores currently active job ids, scored by the time when they started executing. To list all the active job IDs, do this:

```python
registry = StartedJobRegistry(name='my-queue-name', connection=my_redis_conn)
registry. get_job_ids()
```

**Comment by DavidVentura** [comment]
Thanks! Consider mentioning this on the docs
