### ISSUE TITLE
import of config is unsafe

### ISSUE THREAD

**Issue by WeatherGod** [nvie/rq#724]
Why is the config loaded up like an import? That can lead to arbitrary code execution. The only reason I can think of is to utilize the import system, but with only a few variables possible to import, it isn't like these configs should even be complicated in the first place.

I would imagine that it would be fairly trivial to simply utilize ConfigParser() which is in the standard library (and looking forward, configobj() is now available in py3.4+, IIRC). ConfigParser() should be able to read any existing config the same way (provided it isn't utilizing the import system).

If the reason is to be able to fetch information dynamically like from `sys`, that can be easily re-implemented safely via string interpolation and a pre-defined list of keys. Yes, I realize this wouldn't be backwards-compatible, but the security implications here are pretty severe.

**Comment by proofit404** [comment]
`rq worker` executes in the safe environment so it good to have python flexibility in the config file. For example I can import consul module and take settings from it without modifying any rq part. As for security - each job is a pickle string and arbitrary code execution may be done during job fetching.

I don't think removing python configuration worth it.

**Comment by selwin** [comment]
I agree with @proofit404 in that the trade off is not worth it. You should keep your config file secure by following security best practices :)
