### ISSUE TITLE
fetch_job has wrong behaviour

### ISSUE THREAD

**Issue by samuelcolvin** [nvie/rq#728]
I'm kind of amazed this hasn't come up before. It just caused us a very serious error in production.

`queue.fetch_job(job_id)` has no check that the job is actually in that queue, so for example `failed_queue.fetch_job(maybe_this_job_failed_id)` will return a job even if the job hasn't failed!

Surely `fetch_job` should check that `job_id` is in that queue before getting and returning the job?

**Comment by proofit404** [comment]
I agree. If anyone want to fetch job regardless of its status (started jobs, failed jobs) they must use Job class for that.

**Comment by selwin** [comment]
Yeah, this is most definitely a bug. Please open a PR when you can. Will need to mention this backward incompatible change in the next release notes.

**Comment by samuelcolvin** [comment]
Will do, can you assign me to the issue. Might be useful to make me a collaborator so I can add labels etc.?

**Comment by selwin** [comment]
I think only the repo owner @nvie can appoint other collaborators

**Comment by olegarch** [comment]
With this fix there is now way to see jobs in failed queue and rq dashboard is not displaying anything for failed queue. Is it expected?

**Comment by selwin** [comment]
@olegarch this is fixed in https://github.com/nvie/rq/pull/765
