### ISSUE TITLE
Why rq jobs not execute?

### ISSUE THREAD

**Issue by Folyd** [nvie/rq#730]
My RQ jobs never execute? How to fix this?  Please help me. thanks.
<img width="923" alt="screen shot 2016-07-25 at 10 34 37 pm" src="https://cloud.githubusercontent.com/assets/3369694/17105176/ba56e2be-52b8-11e6-9da2-9d7a5ab16667.png">

**Comment by proofit404** [comment]
How about to start worker process?

**Comment by selwin** [comment]
Like @proofit404 mentioned, you'll have to spawn workers to process those jobs. Please check http://python-rq.org for more documentation.
