### ISSUE TITLE
Support for deleting queues

### ISSUE THREAD

**Issue by torfsen** [nvie/rq#731]
I couldn't find a way to delete a queue. There's `Queue.empty`, but that leaves an empty queue. I would like to remove the queue completely.

Currently I'm using the following code:

``` python
queue.empty()
redis_conn.srem(rq.Queue.redis_queues_keys, queue._key)
redis_conn.delete(queue._key)
```

That seems to work, but I'd rather not rely on RQ-internals (e.g. `Queue._key`) in my code. It would therefore be nice if that code was available as `Queue.delete`, similar to `Job.delete`.

I can prepare a PR, let me know if you're interested.

**Comment by selwin** [comment]
PR is welcome for `queue.delete()` :). It should also gives the user option to delete jobs that are found in the queue. Something like `queue.delete(cleanup_jobs=False)` would be nice.

**Comment by theodesp** [comment]
Is there any PR for this as I may do one this week!
