### ISSUE TITLE
Limit number of forks for worker?

### ISSUE THREAD

**Issue by pacahon** [nvie/rq#751]
Hello. What is the best way to limit number of forks in `Worker` class or subclass? 
As I can understand, if I had a lot of heavy jobs in parallel, each would be executed without any delay.

**Comment by proofit404** [comment]
Hi, Sergey.

There are two different behaviors provided by rq.

The first one is accept one job, fork, run job in the child process, wait for it result, get another job.

The second one is the same except fork. SimpleWorker runs job in the same process.

As you can see, jobs are executed sequential, so the rule is simple. Start as many rq worker processes as many jobs you want to run in parallel.

**Comment by pacahon** [comment]
@proofit404 Thanks for response. I should more carefully read the docs and code.
