### ISSUE TITLE
Importing enqueue function on different server

### ISSUE THREAD

**Issue by critlegal** [nvie/rq#759]
Hi there I have flask api which is putting a task onto a redis queue. I have a worker on a different server which I would like to take this task. However whenever I run the worker I get the following error:
`ImportError: No module named api.scripts.dreamify_scripts`

I see that this issue is caused as my API is importing the function I wish to use on the python-rq using the following code: `from ..scripts.dreamify_scripts import *`

However there is no import like such on my workers server. How can I get around this and allow my worker to import the correct function?

Thanks

**Comment by proofit404** [comment]
Install all necessary code at the worker server.

**Comment by jdeepee** [comment]
@proofit404 All the necassary code is on the server but not importable by the worker at path `ImportError: No module named api.scripts.dreamify_scripts` so how can I get my worker to import the module "dremify_scripts" from the current directory?

**Comment by proofit404** [comment]
If you run your worker with `rq worker` from the same directory as your package it won't be available in the python path. Add this directory explicitly to the `PYTHONPATH` environment variable or install it as a package into your virtual environment. Also you can use `pth` files to achieve this.

**Comment by nvie** [comment]
What @proofit404 said, closing this issue.
