### ISSUE TITLE
Adding context to a task

### ISSUE THREAD

**Issue by dfee** [nvie/rq#767]
I can successfully add context to a job from a custom worker by injecting arguments into a job in a subclassed implementation of the worker's `perform_job` method.

However, this context isn't pickleable, so while the work gets done, the job throws an exception when writing back its result. Similarly, this prevents me from enqueueing jobs with queues that are instantiated using `async=False`.

My next approach was to use the job['meta'] to add the context both from my worker (when `async=True`). However, I can't access this metadata when using `async=False` because get_current_job() returns None.

I'm using Pyramid, and on my request object I have a database connection, a customized mailer, etc. configured. I'd like to use these helpers I've built. Is there a suggested approach?

**Comment by selwin** [comment]
RQ's sync mode should mimic its async mode whenever possible. So the correct fix in this case would be to patch ``get_current_job`` to return the current job when it's called in synchronous mode.

**Comment by selwin** [comment]
Please open a PR for this and I'll be happy to review and merge it in :)

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/831
