### ISSUE TITLE
Doc about `async=False` is misleading

### ISSUE THREAD

**Issue by antoine-lizee** [nvie/rq#769]
I understand from #448 that we want ( @selwin ) to have a redis server running as a dependency even when `async=False`. As a result, it is not possible to use the queues without a (working) redis connection.

I, too, would love a built-in test mode that doesn't require having a redis server running. But if we keep the behavior as is, we should update the doc to (i) reflect that the spirit of this is not a unit-test compliant system (ii) fix the snippets on the page http://python-rq.org/docs/ , because it seems to me that, `q = Queue('low', async=False)` will always raise the `NoRedisConnectionException` (from https://github.com/nvie/rq/blob/master/rq/connections.py#L70). (iii) maybe add a small snippet about use of `FakeRedis` for testing purposes?

**Comment by selwin** [comment]
I'm not sure what you mean by "unit testing compliant system", but I believe thats tests that are written well should replicate production environments as closely as possible.

There are some classes of errors that won't be caught if we skip the job persistence. For instance, if `async=False` doesn't try to save Jobs to Redis, crashes that happen when you try to store jobs with arguments that can't be pickled won't be caught.

To make testing more convenient, you could:
1. Use `async=False` so you don't need to run workers separately
2. Use `FakeRedis` if your test setup doesn't include a Redis server

Documentation fixes are always welcome, please open a PR and I'll be happy to merge it in :)

**Comment by antoine-lizee** [comment]
Well - this thread might be a wrong place to start the never-ending debate about the definition of 'unit-testing' :-) 
I would just rather have the boundaries of my a test fall before running a separate redis-server, and from the different issues around here I might not be the only one! But this is definitely a matter of personal views, so my (i) was not really relevant.

Here is the PR for the docs that might be helpful to first-comers: https://github.com/nvie/rq/pull/771

**Comment by hugorodgerbrown** [comment]
Ignoring the unit testing debate - we certainly got caught out by this when we started with rq - it _sounded_ like `async=False` would mean we could remove the redis dependency entirely (again, ignoring whether this is a sensible thing to do or not).
