### ISSUE TITLE
Import Filename is not supported

### ISSUE THREAD

**Issue by crhuber** [nvie/rq#773]
Hello I am just running the following command 

> rq worker -c worker-config

and am getting the following error: 

> 19:32:27 RQ worker u'rq:worker:mes-MacBook-Pro.1485' started, version 0.6.0
> 19:32:27 Cleaning registries for queue: default
> 19:32:27 
> 19:32:27 *** Listening on default...
> 19:32:40 ImportError: Import by filename is not supported.
> Traceback (most recent call last):
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
>     rv = job.perform()
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/job.py", line 498, in perform
>     self._result = self.func(*self.args, **self.kwargs)
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/job.py", line 206, in func
>     return import_attribute(self.func_name)
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
>     module = importlib.import_module(module_name)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: Import by filename is not supported.
> Traceback (most recent call last):
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
>     rv = job.perform()
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/job.py", line 498, in perform
>     self._result = self.func(*self.args, **self.kwargs)
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/job.py", line 206, in func
>     return import_attribute(self.func_name)
>   File "/Users/me/Documents/Development/myapp/venv/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
>     module = importlib.import_module(module_name)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: Import by filename is not supported.
> 19:32:40 Moving job to u'failed' queue

What does it mean and how can i fix it?

**Comment by crhuber** [comment]
updated title

**Comment by proofit404** [comment]
How do you use `Queue.enqueue` method? Looks like you submit something unimportable to the queue.

**Comment by crhuber** [comment]
My mistake I had a typo in my enqueue method. No issue here. Closing
