### ISSUE TITLE
Doc: Clarify how rq works and add note about performance & security

### ISSUE THREAD

**Issue by tuukkamustonen** [nvie/rq#776]
I am a noob to task queues and I find it surprising that rq would pickle the whole task function. I assumed that it would only pickle the parameters, and that the task code would need to be available and imported in the worker. But if I got this right, you just launch a worker, and everything is unpickled and run on-the-fly?

Doesn't that raise concerns about performance - isn't pickling the whole task function rather expensive?

Isn't it insecure also - if attacker gets access to Redis, he can (easily) manipulate the code that will get run?

Maybe I missed it, but shouldn't stuff like this exist in the docs?

**Comment by proofit404** [comment]
Only arguments get pickled, function will be imported by worker. However if you enqueue instance method, the whole object instance will be pickled as well.

**Comment by tuukkamustonen** [comment]
@proofit404 Ok, I guess that makes this ticket invalid then...

So worker auto-resolves the task function based on it's name (e.g. 'my.module.some.task')? I just need to have that (very same) function importable for worker?

**Comment by proofit404** [comment]
Yes, worker resolves function by fully qualified importable name. If you have another function accessible by this name on the worker host it will be evaluated. Also you can submit functions by name.

**Comment by tuukkamustonen** [comment]
> worker resolves function by fully qualified importable name

Thanks for clarifying that. While it may feel self-evident, I think this could be stated in the docs.

Also, I guess my original concern was partially true:

> Doesn't that raise concerns about performance - isn't pickling the whole task function rather expensive?
> 
> Isn't it insecure also - if attacker gets access to Redis, he can (easily) manipulate the code that will get run?

A note should be added about these risks for those cases where you queue instance methods, do you agree?

**Comment by proofit404** [comment]
PR welcome as usual.

P.S. If anyone hacked any of your servers you're fucked any way. So what is the point to worry about pickle?

**Comment by tuukkamustonen** [comment]
Maybe they hack into Redis instance only (it doesn't even have any auth)...

**Comment by selwin** [comment]
As @proofit404 mentioned, PR to improve the documentation is always welcome :) .
