### ISSUE TITLE
Sentry: set transport to HTTPTransport

### ISSUE THREAD

**Issue by Atala** [nvie/rq#777]
It is stated in the doc that:
```
Error delivery to Sentry is known to be unreliable with RQ when using async transports (the default is). So you are encouraged to use the HTTPTransport or RequestsHTTPTransport when creating your client. See the code sample above, or the Raven documentation.
```

It would be nice to go ahead and set this transport directly here: https://github.com/nvie/rq/blob/master/rq/cli/cli.py#L203

(From my experience with the async python client of [segment.io](segment.com) , it is very unlikely logging will work with an async client inside rq)

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/issues/778
