### ISSUE TITLE
Lack of required API for Worker class 

### ISSUE THREAD

**Issue by tarelda** [nvie/rq#779]
I wanted to incorporate RQ to drive data to custom multi-source service. Thus I need to write my own worker implementation. Still there is neither abstract class nor documentation covering Worker. Can somebody at least mark them in code (keyword required or something like that)?

**Comment by selwin** [comment]
This obviously depends on what you want to do. In most cases, subclassing `worker.perform_job` should be enough.

I'm closing this issue, but pull requests to improve the documentation is always welcome.
