### ISSUE TITLE
how to work with asyncio event loop without blocking it

### ISSUE THREAD

**Issue by vertazzar** [nvie/rq#783]
I have a scenario where im using asyncio websockets and everything there should be done with coroutines to accomplish non-blocking

example:

```

@asyncio.coroutine
def work(data):
   results = yield from do_something_with_data(data)
   
   # what the correct code would be that "sends" results to the RQ queue for processing ? # 

```

from examples and the source code i've seen there is no "out of the box" asyncio support, i know that you must use executors to perform any operations that involve IO to prevent the eventloop from blocking

example with executor:
```
def add_to_rq():
   # this code will run in seperate thread to aviod io blocking
   async_results = {}
   q = Queue()
   for x in fib_range:
     async_results[x] = q.enqueue(slow_fib, x)

@asyncio.coroutine
def work(data):
   results = yield from do_something_with_data(data)
   
   yield from asyncio.get_event_loop().run_in_executor(add_to_rq)
```

so my question is, before i start using the library i want to know correct approach provided if there is any

**Comment by proofit404** [comment]
You can look at my reimplementation of rq using asyncio - [aiorq](https://github.com/proofit404/aiorq). Server part isn't working right now, but maybe you can resolve those blocker by your self.

**Comment by vertazzar** [comment]
i have avoided the problem by using separate worker process that will "proxy" the callback params and names

used libs:
https://github.com/jonathanslenders/asyncio-redis
https://github.com/aaugustin/websockets


```

redis_conn = asyncio_redis.Connect(....)

@asyncio.coroutine
def add_to_rq(results):
   redis_conn.publish('rq-proxy', results)

@asyncio.coroutine
def on_websocket_message(data):
   results = yield from do_something_with_data(data)
   
   yield from add_to_rq(results)


## now the rq_proxy.py that uses "syncronous" version - the "redis" package

import redis

# rq Queue
taskqueue = Queue()
conn = redis.StrictRedis(...)
subscriber = conn.subscribe('rq-proxy')
while True:
    instruciton = redis.next_published()
    taskqueue.enqueue(instruction)

```
obviously this is pseudo code but i think someone can use this

also there is obviously fear of redis not passing the message properly, but simple ACK mechanism can prevent that

cheers

**Comment by samuelcolvin** [comment]
Use [arq](https://arq-docs.helpmanual.io).
