### ISSUE TITLE
Worker.handle_job_success overwrites job meta information

### ISSUE THREAD

**Issue by vsajip** [nvie/rq#784]
When a job completes successfully, its `meta` dictionary is overwritten with old values. The use case:

1. When a job is queued, it's done with `meta={'progress: 'Queued'}`.
2. When a job is started, the work function updates with `job.meta['progress'] = 'Started'; job.save()`
3. As the job progresses, its `meta['progress']` info is updated with progress information in the same way.
4. The job completes, and at that point the job on Redis has some value of `meta['progress']` which indicates how far it had progressed.
5. `Worker.handle_job_success` is called with an in-memory copy of the job which has the original progress value of `Queued`. It saves this job instance with an updated status of `finished`, but *omits  to preserve the meta data* before doing this. As a result, the job's `meta` dict is overwritten with the original `{progress: Queued}` value, overwriting any other information in the meta dict.

IMO `Worker.handle_job_success` should get the job's `meta` data and restore it while saving the updated status. See pull request #785 for a fix.

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/pull/781
