### ISSUE TITLE
Question on preloading libraries to run them faster

### ISSUE THREAD

**Issue by nadermx** [nvie/rq#794]
I currently have a `utilities.py` file that has this machine learning function

    from sklearn.pipeline import Pipeline
    from sklearn.feature_extraction.text import CountVectorizer
    from sklearn.naive_bayes import MultinomialNB
    from sklearn.model_selection import train_test_split
    import models
    import random
    
    words = [w.strip() for w in open('words.txt') if w == w.lower()]
    def scramble(s):
        return "".join(random.sample(s, len(s)))
    
    @models.db_session
    def check_pronounceability(word):
    
        scrambled = [scramble(w) for w in words]
    
        X = words+scrambled
        y = ['word']*len(words) + ['unpronounceable']*len(scrambled)
        X_train, X_test, y_train, y_test = train_test_split(X, y)
    
        text_clf = Pipeline([
            ('vect', CountVectorizer(analyzer='char', ngram_range=(1, 3))),
            ('clf', MultinomialNB())
            ])
        text_clf = text_clf.fit(X_train, y_train)
        stuff = text_clf.predict_proba([word])
        pronounceability = round(100*stuff[0][1], 2)
        models.Word(word=word, pronounceability=pronounceability)
        models.commit()
        return pronounceability

Which I then call in my `app.py` 

    from flask import Flask, render_template, jsonify, request
    from rq import Queue
    from rq.job import Job
    from worker import conn
    from flask_cors import CORS
    from utilities import check_pronounceability
    
    app = Flask(__name__)

    q = Queue(connection=conn)
    
    import models
    @app.route('/api/word', methods=['POST', 'GET'])
    @models.db_session
    def check():
        if request.method == "POST":
            word = request.form['word']
            if not word:
                return render_template('index.html')
            db_word = models.Word.get(word=word)
            if not db_word:
                job = q.enqueue_call(check_pronounceability, args=(word,))
            return jsonify(job=job.id)

After reading the [python-rq preformance notes][1] it states 

> A pattern you can use to improve the throughput performance for these
> kind of jobs can be to import the necessary modules before the fork.

Which I then made the `worker.py` file look like this 

    import os
    
    import redis
    from rq import Worker, Queue, Connection
    
    listen = ['default']
    
    redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')
    
    conn = redis.from_url(redis_url)
    import utilities
    
    if __name__ == '__main__':
        with Connection(conn):
            worker = Worker(list(map(Queue, listen)))
            worker.work()
Am I preloading the library correctly in the worker.py file by just importing utilities or is there something else I have to do.

  [1]: http://python-rq.org/docs/workers/

**Comment by doomleika** [comment]
@nadermx:

This seems to be correct. As I check the source code the worker will only fork itself when it's ready to execute a new job from queue.

Importing libraries before executing Worker.work() should free the children processes from importing libraries every time a new job comes.

**Comment by nadermx** [comment]
Alright, just pycharm shows the librarie as not used so wasn't sure if I had to do more

**Comment by doomleika** [comment]
@nadermx Well, Lint tools(such as one built in PyCharm) are not smart enough to detect usage case like those.
