### ISSUE TITLE
When are you going to release a new version?

### ISSUE THREAD

**Issue by lucascarvalho** [nvie/rq#797]

**Comment by superquest** [comment]
Also curious about this. There's a change that landed on master 3 months ago that I need.

**Comment by stratosgear** [comment]
@selwin I'm also looking forward for a new release, for some of the latest stuff. Thanks!

**Comment by selwin** [comment]
I'm hoping to get this issue fixed https://github.com/nvie/rq/pull/812 . Will try to tag a release by the end of this month. Sorry for the wait.

**Comment by selwin** [comment]
Please see https://github.com/nvie/rq/issues/827
