### ISSUE TITLE
AttributeError when pickling class instance method.

### ISSUE THREAD

**Issue by JedS6391** [nvie/rq#799]
I have a service which is called from a Flask web API that needs to do some intensive processing, so it intends to use RQ to queue the tasks so that the API can return immediately and poll the job status. 

The basic setup is:

An API route:
```python
@api.route('/migration/initiate', methods=['POST'])
def migration_initiate():
    json = request.get_json()

    intiation_request, errors = MigrationInitiationRequestSchema().load(json)

    if errors:
        # Schema of data posted is not correct
        return jsonify({'errors': errors})

    job = migration_service.initiate(intiation_request)

    return jsonify({ 'id': job.id })
```

The migration service:

```python
class MigrationService:

    def __init__(self):
        self._queue = Queue('normal', connection=connection)
  
    # Other methods...

    def initiate(self, migration_request):
        job = self._queue.enqueue(self._initiate, migration_request)

        return job

    def _initiate(self, migration_request):
        # Do async processing...
        pass
```

This leads to `AttributeError: Can't pickle local object 'fix_return_type.<locals>._inner'`, which is happening on the line that enqueues the instance method `self._initiate`. 

From what I can tell, RQ supports enqueue class instance methods so I'm not really sure what the problem is but I don't really want to have to separate the processing logic from the service, and even if I did this, I'd want to attach the functionality to a class which (I imagine) would probably still lead to the same problem.

Is this a known issue with enqueue instance methods or is something to do with my class?

**Comment by doomleika** [comment]
Are you using a python interpreter of python3?

    class MigrationService

seems to be an old style class in python2

**Comment by selwin** [comment]
Instance methods can't be pickled reliably so this won't be supported.
