### ISSUE TITLE
worker hang when task result contains unicode characters

### ISSUE THREAD

**Issue by ssikiki** [nvie/rq#806]
My rq version is 0.7.1. I've found that if my task result contains unicode characters, worker'll hang (the process exist, but can't do any new task, and there's no log output). 
I've found a solution:
worker.py   method: perform_job
log_result = "{0!r}".format(as_text(text_type(rv)))
change to
log_result = "{0!r}".format(as_text(isinstance(text_type(rv), unicode) and text_type(rv).encode('utf8') or text_type(rv)))
Could you please check and fix it ?

**Comment by selwin** [comment]
This should be fixed in https://github.com/nvie/rq/pull/817
