### ISSUE TITLE
rq worker does not honor REDIS_PASSWORD setting

### ISSUE THREAD

**Issue by guhcampos** [nvie/rq#809]
I have a settings module to configure the worker, and I'm using -c to pass this module to 'rq worker'.

All settings work fine, including the REDIS_URL and QUEUES settings. The REDIS_PASSWORD seems to be ignored though, as the worker fails with 

`redis.exceptions.ResponseError: NOAUTH Authentication required.`

I have listened for incoming connections on my redis server with 'MONITOR', and can confirm that rq never sends the AUTH command, even with the password configured. 

$ docker exec -ti {redacted} pip3 list | grep rq
rq (0.7.1)

**Comment by selwin** [comment]
Could you please open a PR for this?

**Comment by guhcampos** [comment]
I'm not sure I follow - I don't have a patch, how can I open a PR without one?

**Comment by sankaet** [comment]
was this ever resolved?

**Comment by selwin** [comment]
No, please open a PR if you want to see this addressed. I'm hoping to cut a release end of this month.

**Comment by katichev** [comment]
Why don't you put it into `REDIS_URL`?

```python
REDIS_URL = 'redis://:password@localhost:6379/1'

**Comment by theodesp** [comment]
Shall we close this issue as resolved as @katichev explained?

**Comment by selwin** [comment]
If someone's willing to make a PR for this, I'm willing to accept it :). It's good to give users the flexibility to specify Redis password via the `password` argument. Afterall, it's supported by the Redis library.

**Comment by theodesp** [comment]
I just added some tests for this and it seems that the CLI does pass the options to the connection. Is it something I'm missing?
