### ISSUE TITLE
job expires during execution

### ISSUE THREAD

**Issue by katichev** [nvie/rq#811]
Hi all,

I'm using RQ to perform long running jobs. Sometimes I need to update meta during job execution:
```
def long_job():
    # part A: do stuff
    job = get_current_job()
    job.meta['my_progress'] = 0.5
    job.save()
    # part B: do more stuff
    return result
```
If 'part B' duration is longer than ttl, the job key expires.

As I understand, when I call `get_current_job()`, a new job instance is being created and loaded from redis. Which means that `job.ttl` is also returned from storage, and updated key is not persistent after `job.save()`.

Shall we check current job state in `save()` and do not call `cleanup()` if job is in progress?

**Comment by red-crown** [comment]
+1
Or perhaps we could also add a cleanup or "update" option to the `save()` method.

**Comment by selwin** [comment]
What we can do is introduce a `job.update_meta()` method and make it part of the official API to make it easier for users to update `meta` without accidentally triggering other methods like `cleanup()`.

A PR (along with documentation) for this is welcome :)
