### ISSUE TITLE
how to send job1.result to depending job2?

### ISSUE THREAD

**Issue by pabloa** [nvie/rq#820]
I have 2 tasks:

```Python
def task1( input_string):
    # some long time task
    return result_string1
```
```Python
def task2( input_string):
    # some long time task
    return result_string2
```

When I enqueue task1 I can enqueue it in a job1 on queue1 and I can send parameters to it.

However, when I enqueue task2 in job2 on queue2 (or queue1) and I declare that job2 as *depends_on=job1*, I tried passing a parameter job2.result but its value is *None* always. It seems job2.result is evaluated immediately and it is not evaluated when job1 finishes.

Is it possible to access from task2 to the result of job1 without establish a connection to Redis from task2?

rv worker is connected but it seems the parameter is not sent. If it is not possible, any workaround will be useful.

**Comment by katichev** [comment]
Yes, it is evaluated immediately. So you still need to connect to Redis.

```
def task1(input_string):
    # do work
    return result_string1

def task2(parent_job_id):
    with Connection():
        q = Queue()
        job = q.fetch_job(parent_job_id)
        result_string1 = job.result
    print result_string1
```
```
job1 = q.enqueue(task1, args=(input_string,))
job2 = q.enqueue(task2, args=(job1.id), depends_on=job1)
```

**Comment by pabloa** [comment]
Thank for the answer.

Related question: my Redis Server is not in localhost and it is password protected.
In your example, the lines:
```python
with Connection():
    q = Queue()
```
do those lines know where Redis server is? I would not like to send all the connection information to the job as parameter (but I would do it if there is not other alternative...).

**Comment by katichev** [comment]
They don't, you're right. 
I realized that we already have a connection inside a worker process :) So we can use that one:
```python
from rq import get_current_connection

def task2(parent_job_id):
    with Connection(get_current_connection()):
        q = Queue('foo')
        # ...
```

**Comment by pabloa** [comment]
It worked! Thanks!

**Comment by pabloa** [comment]
@selwin perhaps you would like to put this code snapshot in the documentation. I guess some people could find it useful
