### ISSUE TITLE
Release 0.8.0 to PyPI

### ISSUE THREAD

**Issue by selwin** [nvie/rq#827]
@nvie I've tagged version 0.8.0. Could you please release it on PyPI?

**Comment by sim0nx** [comment]
Any news on this?
Would be great to have it on pypi as well :-)

**Comment by selwin** [comment]
Ping @nvie 😀

**Comment by commandtab** [comment]
Really looking forward to the Unicode fix present in this release :)

**Comment by selwin** [comment]
It's now on PyPI: https://pypi.python.org/pypi/rq
