### ISSUE TITLE
Is there any good examples on message-model such like producer-consumer/pubsub?

### ISSUE THREAD

**Issue by jkryanchou** [nvie/rq#830]
I wonder if there are any examples on message paradigm such like producer-consumer/pubsub by rq. I highly recommend the author or contributors could provide some good examples on them. They could help us to make full use of rq in our production enviroment.

**Comment by selwin** [comment]
RQ is designed as a task queue. If you're looking for a pub/sub mechanism, take a look at Redis' pubsub feature: https://redis.io/topics/pubsub
