### ISSUE TITLE
Job raised exception, still queue notified Job OK

### ISSUE THREAD

**Issue by vaidsu** [nvie/rq#835]
I tried to search for this issue, but couldn't find anything similar. 

I get this exception in my job. 

```bash
  File "/trackit/bugspots.py", line 99, in pims_findcr
    out = subprocess.check_output(cmd, shell=True)
  File "/lib/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: <SNIP>
10:07:06 firex_sync: Job OK (d44f71c9-458a-4707-800d-4dab725be0c3)
```

This made the job send to normal queue and flush it out. I have seen timeout exceptions properly putting the job in failed queue. Should I catch these exceptions internally and then flag some other exception that RQ understands? 

Please help. These intermittent job failures didn't provide any notifications to the dev-ops pool thus losing some data due to these hidden failures.

**Comment by selwin** [comment]
As long as your function/job raises an (uncaught) exception, RQ should marks the job as failed.
