### ISSUE TITLE
python script to start worker

### ISSUE THREAD

**Issue by rizplate** [nvie/rq#839]
Can I start the worker via rq internal python api and dynamically pause and assign them to queue?   

i.e. I want to write a python script that is reading a file periodically for queue-name and when it reads the name it starts 5 workers on that queue .

**Comment by selwin** [comment]
I suppose, but you'll have to build your own process management because each worker runs in a separate process. Take a look at https://github.com/nvie/rq/blob/master/rq/cli/cli.py#L183 for an example of how to spin up a worker.
