### ISSUE TITLE
How to get all Finished Jobs by Queue.?

### ISSUE THREAD

**Issue by jkryanchou** [nvie/rq#842]
@selwin Is PR #391 could get the FinishedQueue? I haven't see any modifications of it could show me to get the FinishedQueue directly.

**Comment by jkryanchou** [comment]
Anyone could help me out with this issue?

**Comment by scroogie** [comment]
Have a look at registry.py. There are multiple registries available: StartedJobRegistry, FinishedJobRegistry and DeferredJobRegistry, where you can get the job_ids from.

**Comment by jkryanchou** [comment]
@scroogie OK, I have got insight into source code finally got the same way as you said. While registry was store as `zset`. It wasn't convenient pop as a Queue. It was required to implement a `pop` interface to do it.

**Comment by jkryanchou** [comment]
@scroogie OK, I have got insight into source code finally got the same way as you said. While registry was store as `zset`. It wasn't convenient pop as a Queue. It was required to implement a `pop` interface to do it.

**Comment by selwin** [comment]
The easiest way to get all jobs in a registry would be:
```python
registry = FinishedJobRegistry('default', connection=redis)
job_ids = registry.get_job_ids() # You can then turn these into Job instances
```

**Comment by jkryanchou** [comment]
@selwin OK, Got it. Thanks a lot

**Comment by flavioribeiro** [comment]
Just to complement this, after getting the list of job_ids from the registry, I could use:

```
from rq import Job
from redis import Redis

job.Job.Fetch("job-id-here", connection=Redis())
```

to fetch the real job object from the queue.
