### ISSUE TITLE
cleanup of completed jobs?

### ISSUE THREAD

**Issue by rizplate** [nvie/rq#849]
Does this thing cleans up the completed jobs?

i.e. if I set the max-memory, memory policies does it work correctly?

I am getting memory issues while running large number of jobs, I know that redis is memory bound but does it clean itself after sometime, to preserve memory?

**Comment by Florents-Tselai** [comment]
"A job has two TTLs, one for the job result and one for the job itself. This means that if you have job that shouldn't be executed after a certain amount of time, you can define a TTL as such:"

http://python-rq.org/docs/jobs/

**Comment by rizplate** [comment]
Thanks, 
what if the job is successfully executed or erred . i.e. if it executed and its result has been cleaned after the job-result ttl.
does the job itself gets cleaned?

so lets say I run 100 jobs today and no jobs for a week, will the jobs information gets cleaned after a week ?

**Comment by selwin** [comment]
Successful jobs will be automatically cleared by Redis, based on `job.result_ttl`.

Failed jobs won't be automatically deleted, you'll have to delete them manually.
