### ISSUE TITLE
Access shared data from multiple jobs

### ISSUE THREAD

**Issue by bee-keeper** [nvie/rq#850]
Hi there,

First of all, thanks a lot for RQ.  I have an implementation query and am hoping to get some advice on best practice.

I have around 20 workers consuming an API.  The API uses a token mechanism which I have recently discovered is limited to around 10 available tokens.  Currently each job is in charge of getting their own token to access the API but obviously this is causing half the jobs to fail as there are not enough tokens to go round.

Therefore, I'm thinking to share one token between all the jobs.  The catch is these tokens expire quite quickly so jobs would need a way to refresh the 'global' token before it expires.  Do you have an opinion on how best to do this?  I'm using Django RQ btw.

Thanks in advance,

**Comment by selwin** [comment]
There's nothing in RQ that facilitates data sharing between jobs. I'm afraid the easiest way to do this is to build this into your jobs (check for latest available token in DB or Redis before issuing a new one).
