### ISSUE TITLE
Python versions supported ?

### ISSUE THREAD

**Issue by jflebeau** [nvie/rq#853]
In the doc, I don't see any explicit references to versions of Python supported, any potential issues with 3.4+ ?

**Comment by scottwernervt** [comment]
There shouldn't be any issues with 3.4 since rq is tested on "2.6","2.7","3.3","3.4","3.5","3.6","3.6-dev","pypy" according to [.travis.yml](https://github.com/nvie/rq/blob/master/.travis.yml). In addition, all tests are passing at https://travis-ci.org/nvie/rq.
