### ISSUE TITLE
workers share the same connection to process jobs

### ISSUE THREAD

**Issue by seanlook** [nvie/rq#869]
I have lots of jobs queuing queries/sql to execute in target database. It create database connection for **every** sql, but it's no need in fact. It can execute many SQLs within the same connection. I think it as a performance impact.

for example:
```
def write_to_db(sql):
    dbconn = pymysql.Connect(**dbinfo)
    cur = dbconn.cursor()
    cur.execute(sql)
    dbconn.close()
```
Hundreds of thousands SQLs will lead to create too much connecitons. When I try place `dbconn = pymysql.Connect(**dbinfo)` out of the function, the result is the same.
When I give connection as a argument to `q.enqueue(write_to_db, (dbconn, sql))`, it fails because of connection can't be pickled.

In documentation section *Performance notes*, **library_that_you_want_preloaded** can not give dbconn to work().

So any advice?

**Comment by selwin** [comment]
If you're looking at hundreds of thousands of connections, I think you should use a connection pooler so your workers can share DB connections.

If you simply want to use one connection per worker (as opposed to creating a new one for every job), try using `SimpleWorker`. This worker class doesn't call `os.fork()` when performing jobs. This way, you can open a DB connection on the worker level and use it when processing jobs.

Hope this helps.

**Comment by piotr-wasilewski** [comment]
Any example how to achieve that?

**Comment by theodesp** [comment]
Take a look at the documentation for [custom-worker-classes](https://python-rq.org/docs/workers/#custom-worker-classes)

For example you can make a MysqlWorker that has a connection pool ready.

See an example using a gevent pool here:

https://github.com/zhangliyong/rq-gevent-worker/blob/master/rq_gevent_worker.py
