### ISSUE TITLE
Why there is no default ttl for job ?

### ISSUE THREAD

**Issue by eromoe** [nvie/rq#873]
If I don't set ttl to a job, there would be many `rq:job:e680d99e-4526-4df1-bd0d-92fb8b96902f` in redis.
No need much time, redis full of such things, and can not see other.

**Comment by selwin** [comment]
You can pass in a `ttl` argument to `queue.enqueue` if you want your jobs to have ttls. I think automatically deleting unfinished jobs is not the right default. Depending on the workload and length of the queue, some jobs may not be processed for a long time.
