### ISSUE TITLE
Can have non-forking workers?

### ISSUE THREAD

**Issue by stuz5000** [nvie/rq#875]
I'm working on a modelling application and get big speedups by maintaining an in-memory LRU-cache.
It seems that RQ workers fork in order to execute each job meaning that, I can write to my LRU-cache, but its contents will be immediately discarded.

Is it possible for me to manage my own workers like so:
```
def worker_daemon():
    while True:
        job = q.get_next()
        result = job() # Update LRU
        q2.put(result)  
```
... and if I want multiple asynchronous workers on a host, I could launch the above in multiple threads.

I'm not concerned about the GIL as most of the heavy lifting for my app happens outside of the GIL in C.

**Comment by theodesp** [comment]
You can. Take a look at the custom worker classes here
http://python-rq.org/docs/workers/#custom-worker-classes

You can implement your own non-forking worker for example by overriding the `execute_job` method here 
https://github.com/nvie/rq/blob/master/rq/worker.py#L585-L594

**Comment by selwin** [comment]
RQ also has a `SimpleWorker` class that doesn't fork (perfect for testing or other situations that require jobs to be executed in the same thread). https://github.com/nvie/rq/blob/master/rq/worker.py#L880
