### ISSUE TITLE
CSS not found at http://python-rq.org/docs/

### ISSUE THREAD

**Issue by mike-pomodoro** [nvie/rq#879]
There's no CSS on http://python-rq.org/docs/:

screen.css Failed to load resource: the server responded with a status of 404 (Not Found)
syntax.css Failed to load resource: the server responded with a status of 404 (Not Found)
screen.css Failed to load resource: the server responded with a status of 404 (Not Found)
syntax.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by theodesp** [comment]
This issue has been fixed.
