### ISSUE TITLE
How can I print log in rq worker?

### ISSUE THREAD

**Issue by jiajunhuang** [nvie/rq#884]
Hello, I start multiple worker by this way:

```python
import multiprocessing

from raven import Client
from raven.transport.http import HTTPTransport
from redis import StrictRedis
from rq import Worker
from rq.contrib.sentry import register_sentry

from itachi.config import config


def start_worker(queues):
    client = Client(config.SENTRY_DSN, transport=HTTPTransport)
    worker = Worker(
        queues=queues,
        connection=StrictRedis.from_url(config.WORKER_BROKER)
    )
    register_sentry(client, worker)
    worker.work()


def work():
    workers = []
    for i in range(config.WORKER_NUMBER):
        p = multiprocessing.Process(
            target=start_worker, args=(["to_user", "device"],)
        )
        p.start()
        workers.append(p)

    for i in range(config.WORKER_PROJECT_NUMBER):
        p = multiprocessing.Process(
            target=start_worker, args=(["to_project"],)
        )
        p.start()
        workers.append(p)

    for i in workers:
        i.join()


if __name__ == "__main__":
    work()
```

`worker.worker()` use the default logging level, so it's "INFO", and I'm using `logging.info(...)` in my job,
but I can't see any log.

**Comment by jlopex** [comment]
The log_level set on the worker is referring to the worker (internal) logs. 

You can get the logger by doing " logger = logging.getLogger('rq.worker')", but personally I don't recommend use the 'rq.worker' logging infrastructure for your own application logic.

Most probably you'll need to setup your own logger for your application, see https://docs.python.org/2/library/logging.html for more info on setting your own logger.

**Comment by jiajunhuang** [comment]
I've got the reason, because I'm using the root logger by this way:

```python
import logging
logging.info("hello")
```

but the default logging level for root logger is `WARNING`, so it will not print.

a dirty fix is:

```python
import logging

root_logger = logging.getLogger()
root_logger.setLevel(logging.INFO)
```
