### ISSUE TITLE
Queues clearing on Deployment

### ISSUE THREAD

**Issue by lukashambsch** [nvie/rq#891]
When we deploy new code and there are pending jobs in rq, they seem to fail because the code is momentarily missing. This makes sense. I was wondering if there is a recommended way of dealing with something like this. I could re-queue all of the failed jobs, but we have to many additional failed jobs at the moment. So, this would cause a lot of unnecessary re-running of jobs.

If anyone has any suggestions, I would really appreciate it!

**Comment by selwin** [comment]
You should stop/suspend workers before re-enabling them after deployment if your code could go missing during deployment.
