### ISSUE TITLE
Documentation link URL for Monitoring

### ISSUE THREAD

**Issue by lozadaOmr** [nvie/rq#894]
On the URL `http://python-rq.org/docs/workers/`

Link to see the monitoring page has an extra 'docs/workers' in url

# Worker names

Workers are registered to the system under their names, see [monitoring](http://python-rq.org/docs/workers/docs/monitoring/). By default, the name of a worker is equal to the concatenation of the current hostname and the current PID. To override this default, specify the name when starting the worker, using the --name option.

--- 
Should it be just `http://python-rq.org/docs/monitoring/`

**Comment by selwin** [comment]
Fixed. Thanks!
