### ISSUE TITLE
Prioritize workers by speed

### ISSUE THREAD

**Issue by torokati44** [nvie/rq#898]
I use RQ to run jobs on a cluster of machines, in batches of varying sizes. The cluster is heterogeneous, so some of them are older laptops, some of them are brand new workstations. I run as many `rq worker` processes on each machine as the number of logical cores in them.
If the batch at hand consists of thousands of jobs, each of them taking minutes to complete, it pays off to use all available processing power. This is why the laptops are part of the cluster.
However, if a particular batch is made up of just a couple jobs, each running for over ten minutes, I would like to have only the workstation(s) running them.
Is there a way to somehow add a "weight" parameter for each worker, so the faster ones pop the jobs first? Or is there a way to emulate this behaviour otherwise?

**Comment by nzjrs** [comment]
probbably related to https://github.com/nvie/rq/issues/889 and to custom worker classes where I imagine such policy could/should be applied

**Comment by selwin** [comment]
At the moment, job is popped by workers off the queue on a FIFO basis.

It will be quite difficult to change this behavior, but what you can do is create two separate queues, one for longer tasks and another for quicker ones. The workers on your laptops can then listen for jobs on the latter queue.

I'm closing this issue for now, but please reopen if you have another idea.

**Comment by torokati44** [comment]
I know that queues are FIFO. I don't want to change the order in which jobs are processed (in fact this can be controlled easily, by changing the insertion/enqueueing order).
I want to change which workers process the jobs if there are fewer jobs than workers.

I can't create two queues, because there aren't two kinds of jobs, "quick" and "long". Perhaps I should have put less emphasis on the processing duration of the jobs. It is next to impossible to estimate how long any given job will take in my case.

The only thing I wish for is that if I enqueue 6 jobs (without considering their duration) into a single queue on which 24 workers listen (8 on 3 different machines each), then those 6 jobs would be processed by a subset of the 8 workers on the fastest computer only.

I also can't create separate queues for workers, because they might come online and go offline over time. Also, that would miss the point of the multi-worker queuing entirely.

Does this make any sense?

**Comment by nzjrs** [comment]
I agree this was an odd reason to closet this bug.

For reference I did something similar with a custom worker class as I indicated above. I pop the job, check some metadata I have attached to see if I should run it, if so run the job, if not push it back to the end of the queue. I have to sleep a bit to stop pushing / popping forever, but its a working prototype while I consider a better way to do this.

**Comment by torokati44** [comment]
I'm not sure that a single worker alone can judge well enough if it should process any given job at a given moment. In my mind it is a function of the current set of jobs, and workers - attached to them their proposed "weight" parameter, describing their relative processing power.
I feel like the desired behavior could perhaps emerge from a slight change in the way the workers subscribe to the events on the queue. But I don't know the internals of RQ well enough to know for sure.

**Comment by nzjrs** [comment]
It's up to you what other things you consider in the time after you have popped the job and before you start it or push it back onto the queue again. You can walk all other queues and all others workers in redis and make as complicated decision as you like.
