### ISSUE TITLE
Support json as dumped string in message queue?

### ISSUE THREAD

**Issue by jiajunhuang** [nvie/rq#909]
Hello, I've read code in `job.py`, and I found that it's using `pickle.loads` & `pickle.dumps`. Do you have any plan to use JSON instead of pickle? By using JSON, the protocol can be generic, multi-programming language support.

**Comment by selwin** [comment]
Yes, certainly. Would welcome a PR for this. Please see this issue for reference: https://github.com/nvie/rq/issues/369

I'm closing this as duplicate.
