### ISSUE TITLE
Severe problems with the documentation for release v0.10.0

### ISSUE THREAD

**Issue by samuelcolvin** [nvie/rq#914]
https://github.com/nvie/rq/compare/master...v0.10.0

Currently fairly confusing that the release docs are not visible on master, this is also causing pyup to show no changelog.

In addition tests are failing, I guess:
* either fix the circleCI key or remove circleCI
* and, either fix pypy or make it optional.

**Comment by samuelcolvin** [comment]
Also the changelog for v0.10.0 misses numerous things that have changed since v0.9.2!!!

https://github.com/nvie/rq/compare/v0.9.2...v0.10.0

**Comment by samuelcolvin** [comment]
@selwin @nvie have you seen this? Please can we fix.

**Comment by selwin** [comment]
I made the release from my work PC. I think what happened is that the documentation and version bump that I worked on wasn't pushed to master successfully. I'll only have access to that PC work on Monday.

I have updated `CHANGES.md` on the master branch, but I'll have to update the rest on Monday.

Regarding the tests:
1. All tests on Travis should pass, sometimes it's just a matter of restarting the jobs
2. Only @nvie can remove CircleCI integration. Could you please help?

**Comment by samuelcolvin** [comment]
thanks.

**Comment by nvie** [comment]
Hey there, happy to help if there's anything being blocked by me. Not sure what the issue is though. We don't use CircleCI (AFAIK), Travis tests are passing fine, but Coveralls seems to be failling. It fails because test coverage has decreased, i.e. new, uncovered, lines were added. So it's doing what it was intended for?

**Comment by samuelcolvin** [comment]
I don't think that's correct:

![image](https://user-images.githubusercontent.com/4039449/34570675-6511f4d2-f164-11e7-8053-63b16b38d33d.png)

Looks to me like CircleCI is connected but not setup correctly.

**Comment by nvie** [comment]
Ah, gotcha! Thanks for pointing me there. No idea how Circle was enabled here, but it seems fixed now 👍

**Comment by selwin** [comment]
@nvie while you're here, what are your thoughts on making @samuelcolvin a contributor so he can help with docs, triaging issues etc? :)

**Comment by nvie** [comment]
Sounds good! This project can use all the help/love it can get, and I'm unfortunately not using it anymore myself currently (since I'm not using Python that much anymore these days).  I have considered moving the project to either [Jazzband](https://github.com/jazzband) or an `rq` organization instead of keeping it under my personal account.

I'd love to hand the stick to you and whoever you think would be a good contributor to this project.

@samuelcolvin: Welcome! I have just added you to the project as a collab. Can you also send me your PyPI username, so I can add you as a package maintainer? Thanks!

**Comment by Florents-Tselai** [comment]
+1 for a dedicated RQ organization. There some nice rq-related tools out there like rq-dashboard that could ideally live under a common roof.

**Comment by samuelcolvin** [comment]
Thanks guys. I'll do my best to help.

Closing this as it looks to be fixed.

**Comment by samuelcolvin** [comment]
rq organisation sounds like a good idea to me. Would be good to get stuff like `django-rq` into the same place.

**Comment by samuelcolvin** [comment]
also there are other changes to the repo that might be a good idea like moving from coveralls to codecov that I believe currently require @nvie could be done by any collaborator if the repo was on an organisation.

**Comment by selwin** [comment]
+1 for RQ organization.

**Comment by nvie** [comment]
Hey @selwin and @samuelcolvin — I have just moved the RQ project away from under my username and into a dedicated organization for managing all RQ related projects: https://github.com/rq.  Feel free to move any RQ related projects into this umbrella organization (rq-scheduler, rq-dashboard, etc.)!  I have invited the both of you to the organization.

Please ping me anytime so I can help out if anything is still being blocked by me or my account.

From here, I'd like to thank you both, and all other 123 contributors, for your fantastic work in keeping RQ maintained and moving forward throughout the years.  Even though it's already been the case practically for a long while now, this marks the end of my active involvement in the project.

RQ started as a fun little project, and I'm proud of what the project has become today.  Having its own GitHub org is what the project and the community it spawned deserve.

Cheers to a long and prosperous future! ✨🍀🍻

**Comment by samuelcolvin** [comment]
Thanks @nvie for the organisation.

Also, this seems like a good place to say thanks for rq in general:

It's been a cornerstone of how TutorCruncher functions since we started rebuilding the platform in 2014 and I imagine it will continue to be for many years to come.

rq also heavily inspired the async variant [arq](https://github.com/samuelcolvin/arq) which I maintain and use on lots of other projects. Thank you.

**Comment by nvie** [comment]
> rq also heavily inspired the async variant arq which I maintain and use on lots of other projects. Thank you.

That's a _fantastic_ name for a project 💯
